// RECIPIES!!!!!

addRecipe("bread+peanut_butter+jam","Peanut Butter & Jelly Sandwich");
addRecipe("bread+cheese+butter","Grilled Cheese Sandwich");
addRecipe("bread+bacon+lettuce+tomato+mayonnaise","BLT");
addRecipe("flour+milk+egg+sugar","Classic Pancakes");
addRecipe("bread+egg+milk+butter","French Toast");
addRecipe("flour+water+yeast+salt","Basic Bread Loaf");
addRecipe("rice+chicken+broth+vegetable","Chicken and Rice");
addRecipe("pasta+tomato_sauce+beef","Spaghetti Bolognese");
addRecipe("pasta+olive_oil+garlic+parmesan","Spaghetti Aglio e Olio");
addRecipe("potato+oil+salt","French Fries");
addRecipe("potato+butter+milk","Mashed Potatoes");
addRecipe("tomato+broth+cream","Creamy Tomato Soup");
addRecipe("chicken+broth+vegetable","Chicken Soup");
addRecipe("fish+lemon+butter","Pan-seared Fish with Lemon Butter");
addRecipe("shrimp+garlic+butter","Shrimp Scampi");
addRecipe("tuna+mayonnaise+bread","Tuna Sandwich");
addRecipe("egg+mayonnaise+bread","Egg Salad Sandwich");
addRecipe("lettuce+parmesan+chicken","Chicken Caesar Salad");
addRecipe("flatbread+cheese+chicken","Chicken Quesadilla");
addRecipe("corn_chip+cheese+jalapeno","Loaded Nachos");
addRecipe("beef+potato+carrot+onion","Beef Stew");
addRecipe("ground_meat+tomato_sauce+herbs","Meatballs in Tomato Sauce");
addRecipe("bread+egg+cheese","Breakfast Sandwich");
addRecipe("rice+egg+soy_sauce","Fried Rice");
addRecipe("bread+butter+garlic+parsley","Garlic Bread");
addRecipe("potato+cheese+bacon","Loaded Baked Potato");
addRecipe("flour+egg+milk+butter","Crepes");
addRecipe("oat_seed+milk+honey","Oatmeal");
addRecipe("bread+mozzarella+tomato+basil","Caprese Sandwich");
addRecipe("avocado+lime+salt+corn_chip","Guacamole and Chips");
addRecipe("black_bean+rice+pepper+cheese","Veggie Burrito");
addRecipe("lentil+carrot+onion+tomato","Lentil Soup");
addRecipe("mushroom+cream+garlic","Creamy Mushroom Sauce");
addRecipe("egg+cheese+milk","Omelette");
addRecipe("pasta+cream+mushroom+parmesan","Fettuccine Alfredo");
addRecipe("tomato+sugar+vinegar+onion","Salsa Fresca");
addRecipe("cucumber+vinegar+sugar","Quick Pickles");
addRecipe("corn+butter+salt","Corn on the Cob");
addRecipe("coconut_milk+rice+sugar","Coconut Rice Pudding");
addRecipe("banana+flour+egg+sugar","Banana Bread");
addRecipe("apple+flour+sugar+butter","Apple Pie");
addRecipe("salmon+lemon+dill","Grilled Salmon with Dill");
addRecipe("tofu+soy_sauce+ginger","Gingered Tofu");
addRecipe("chickpea+garlic+lemon+olive_oil","Hummus");
addRecipe("shrimp+batter+oil","Fried Shrimp");
addRecipe("rice+beans+cheese+salsa","Burrito Bowl");
addRecipe("bread+jam+butter","Jam Toast");
addRecipe("pasta+olive_oil+garlic+chili","Pasta Arrabbiata");
addRecipe("sugar+milk+egg_yolk+flour","Custard Tart");
addRecipe("beef+onion+salt+pepper","Pan-Seared Steak");
addRecipe("dough+sauce+cheese","Pizza");
addRecipe("flour+butter+sugar+egg","Cookies");
addRecipe("cream+fruit+sugar","Fruit Parfait");
addRecipe("coffee+milk+sugar","Cafe Latte");
addRecipe("milk+ice_cream+syrup","Milkshake");
addRecipe("root_beer+ice_cream","Root Beer Float");
addRecipe("coffee+milk+ice","Iced Coffee");
addRecipe("tea+milk+sugar","Milk Tea");
addRecipe("flour+butter+salt","Pie Crust");
addRecipe("batter+sugar+butter","Cake");
addRecipe("dough+tomato_sauce+cheese+pepperoni","Pepperoni Pizza");
addRecipe("egg+flour+milk+sugar","Crepe Batter");
addRecipe("rice+vinegar+sugar+seaweed+fish","Sushi Roll");
addRecipe("potato+egg+onion+flour","Potato Pancakes");
addRecipe("cornmeal+water+salt","Polenta");
addRecipe("potato+onion+egg+flour","Latkes");
addRecipe("bread+butter+garlic","Garlic Toast");
addRecipe("mango+banana+milk","Tropical Smoothie");
addRecipe("chocolate+milk+sugar","Hot Chocolate");
addRecipe("tomato+mozzarella+basil","Caprese Salad");
addRecipe("bread+olive_oil+garlic","Bruschetta");
addRecipe("chicken+barbecue_sauce","BBQ Chicken");
addRecipe("pork+soy_sauce+ginger+garlic","Pork Stir Fry");
addRecipe("beef+onion+soy_sauce","Beef and Onion Stir Fry");
addRecipe("egg+flour+milk+butter","French Omelette");
addRecipe("spinach+ricotta+egg+dough","Spinach Ricotta Pie");
addRecipe("rice+chicken+coconut_milk","Coconut Chicken Rice");
addRecipe("noodles+peanut_butter+soy_sauce+vinegar","Peanut Noodles");
addRecipe("potato+cheese+cream","Potato Gratin");
addRecipe("beans+tomato+spice","Chili Con Carne");
addRecipe("bread+garlic+cheese","Cheesy Garlic Bread");
addRecipe("fruit+sugar+lemon","Fruit Compote");
addRecipe("cream+chocolate+sugar","Chocolate Mousse");
addRecipe("chicken+lemon+butter+parsley","Lemon Butter Chicken");
addRecipe("beef+red_wine+onion+thyme","Beef Bourguignon");
addRecipe("duck+orange+sugar","Duck \u00e0 l'Orange");
addRecipe("egg+milk+sugar+vanilla","Cr\u00e8me Br\u00fbl\u00e9e");
addRecipe("potato+herb+salt+oil","Roasted Potatoes");
addRecipe("salad_leaves+goat_cheese+beetroot+walnut","Beetroot & Goat Cheese Salad");
addRecipe("zucchini+tomato+garlic+olive_oil","Ratatouille-Style Veggies");
addRecipe("rice+vinegar+sugar+egg","Tamago Sushi");
addRecipe("bagel+cream_cheese+smoked_salmon","Smoked Salmon Bagel");
addRecipe("bagel+cream_cheese+tomato","Tomato Cream Cheese Bagel");
addRecipe("bread+avocado+egg+salt","Avocado Toast with Poached Egg");
addRecipe("tortilla+chicken+lettuce+tomato","Chicken Wrap");
addRecipe("tortilla+black_bean+corn+salsa","Black Bean & Corn Wrap");
addRecipe("bread+roast_beef+horseradish+lettuce","Roast Beef Sandwich");
addRecipe("bread+ham+cheese+mustard","Ham & Cheese Sandwich");
addRecipe("bread+turkey+cranberry+lettuce","Turkey & Cranberry Sandwich");
addRecipe("ciabatta+mozzarella+tomato+basil","Caprese Ciabatta");
addRecipe("pita+hummus+grilled_veg","Grilled Veg Pita with Hummus");
addRecipe("naan+chicken_tikka+yogurt","Chicken Tikka Naan Wrap");
addRecipe("torta_bread+refried_bean+cheese+avocado","Mexican Torta");
addRecipe("baguette+brie+apple","Brie & Apple Baguette");
addRecipe("pretzel+butter+salt","Buttered Pretzel");
addRecipe("english_muffin+egg+cheese+ham","Egg Muffin Sandwich");
addRecipe("wrap+falafel+tzatziki+lettuce","Falafel Wrap with Tzatziki");
addRecipe("lavash+smoked_salmon+cream_cheese+capers","Smoked Salmon Lavash Roll");
addRecipe("lettuce+tomato+cucumber+olive_oil+vinegar","Simple Garden Salad");
addRecipe("spinach+strawberry+almond+goat_cheese","Spinach & Strawberry Salad");
addRecipe("kale+quinoa+chickpea+lemon","Kale & Quinoa Salad");
addRecipe("arugula+pear+parmesan+walnut","Arugula Pear Salad");
addRecipe("tomato+mozzarella+basil+olive_oil","Caprese");
addRecipe("cucumber+yogurt+dill","Cucumber Yogurt Salad");
addRecipe("corn+black_bean+tomato+cilantro","Mexican Street Corn Salad");
addRecipe("lettuce+avocado+shrimp+citrus_dressing","Shrimp & Avocado Salad");
addRecipe("mixed_greens+goat_cheese+pear+walnuts","Autumn Mixed Greens Salad");
addRecipe("couscous+mint+tomato+cucumber","Couscous Salad");
addRecipe("tomato+crouton+cream+basil","Creamy Tomato Bisque");
addRecipe("lentil+smoked_paprika+carrot+celery","Smoky Lentil Soup");
addRecipe("miso+tofu+seaweed+scallion","Miso Soup with Tofu");
addRecipe("broth+noodles+chicken+soy_sauce","Asian Chicken Noodle Soup");
addRecipe("potato+leek+cream+butter","Potato Leek Soup");
addRecipe("beef+barley+carrot+celery","Beef and Barley Soup");
addRecipe("clam+potato+cream+celery","New England Clam Chowder");
addRecipe("tomato+red_lentil+cumin","Red Lentil Soup");
addRecipe("carrot+ginger+cream","Carrot Ginger Soup");
addRecipe("pumpkin+cream+nutmeg","Pumpkin Soup");
addRecipe("pasta+carbonara_sauce+egg_yolk+parmesan+pepper","Spaghetti Carbonara");
addRecipe("lasagna_noodle+ground_beef+ricotta+tomato_sauce+mozzarella","Classic Lasagna");
addRecipe("penne+arrabbiata_sauce+chili","Penne all'Arrabbiata");
addRecipe("gnocchi+tomato_sauce+mozzarella","Gnocchi with Tomato & Mozzarella");
addRecipe("ravioli+ricotta+spinach+butter_sage","Ricotta Ravioli with Sage Butter");
addRecipe("tagliatelle+wild_mushroom+cream","Wild Mushroom Tagliatelle");
addRecipe("bucatini+amatriciana_sauce+guanciale","Bucatini all'Amatriciana");
addRecipe("pasta+pesto+pine_nuts+parmesan","Pesto Pasta");
addRecipe("spaghetti+clams+white_wine+garlic","Spaghetti alle Vongole");
addRecipe("macaroni+cheddar+milk+butter","Classic Mac & Cheese");
addRecipe("rice+soy_sauce+egg+scallion","Egg Fried Rice");
addRecipe("rice+vinegar+sugar+seaweed+raw_fish","Nigiri-style Sushi");
addRecipe("rice+vinegar+sugar+seaweed+avocado+crab","California Roll");
addRecipe("rice+coconut_milk+banana","Sweet Coconut Rice");
addRecipe("rice+turmeric+chicken+saffron","Arroz con Pollo");
addRecipe("noodles+peanut_sauce+cucumber+carrot","Cold Peanut Noodles");
addRecipe("rice+soy_sauce+ginger+chicken","Teriyaki Chicken Rice Bowl");
addRecipe("rice+beans+plantain+avocado","Caribbean Rice Plate");
addRecipe("quinoa+black_bean+corn+lime","Quinoa & Black Bean Salad");
addRecipe("noodles+char_siu+bok_choy","Char Siu Noodles");
addRecipe("salmon+soy_sauce+ginger+sesame","Soy Glazed Salmon");
addRecipe("shrimp+garlic+white_wine+butter","Garlic White Wine Shrimp");
addRecipe("fish+cornmeal+oil+lemon","Southern Fried Fish");
addRecipe("crab+butter+garlic+parsley","Garlic Butter Crab");
addRecipe("scallop+lemon+butter+garlic","Pan-Seared Scallops");
addRecipe("tuna+olive_oil+lemon+capers","Seared Tuna with Capers");
addRecipe("mussels+white_wine+tomato+garlic","Mussels in White Wine");
addRecipe("octopus+potato+olive_oil+lemon","Grilled Octopus with Potatoes");
addRecipe("salmon+maple_glaze","Maple Glazed Salmon");
addRecipe("shrimp+rice+spice","Jambalaya-style Shrimp & Rice");
addRecipe("chicken+lemon+rosemary+olive_oil","Roast Lemon Rosemary Chicken");
addRecipe("beef+red_wine+mushroom+onion","Beef Bourguignon (stew)");
addRecipe("pork+soy_sauce+honey+garlic","Honey Soy Glazed Pork");
addRecipe("lamb+garlic+rosemary+wine","Herb Roasted Lamb");
addRecipe("duck+hoisin+scallion+cucumber","Peking Duck-style Wrap");
addRecipe("meatball+tomato_sauce+pasta","Meatballs & Spaghetti");
addRecipe("beef+black_pepper+sauce","Pepper Steak");
addRecipe("chicken+curry_powder+coconut_milk","Chicken Curry");
addRecipe("pork+apple+sage","Pork with Apple & Sage");
addRecipe("veal+marsala+mushroom","Veal Marsala");
addRecipe("tortilla+carne_asada+onion+cilantro","Carne Asada Tacos");
addRecipe("tortilla+fish+slaw+lime","Fish Tacos with Slaw");
addRecipe("tortilla+chicken+cheese+salsa","Chicken Quesadilla");
addRecipe("taco_shell+ground_beef+lettuce+cheese","Classic Ground Beef Taco");
addRecipe("tortilla+vegetable+black_bean+cheese","Veggie Quesadilla");
addRecipe("masa+chicken+pepper_cheese","Chicken Tamales");
addRecipe("enchilada_tortilla+chicken+enchilada_sauce+cheese","Chicken Enchiladas");
addRecipe("tortilla+barbacoa+onion+cilantro","Barbacoa Tacos");
addRecipe("tortilla+al pastor+pineapple","Al Pastor Taco");
addRecipe("tortilla+chorizo+potato+egg","Chorizo & Potato Breakfast Taco");
addRecipe("potato+rosemary+olive_oil+salt","Roasted Rosemary Potatoes");
addRecipe("green_beans+almond+butter","Green Beans Almondine");
addRecipe("brussels_sprout+bacon+maple","Roasted Brussels Sprouts with Bacon");
addRecipe("corn+butter+parmesan+chili","Mexican Street Corn (Elote)");
addRecipe("mushroom+garlic+butter","Sauteed Garlic Mushrooms");
addRecipe("asparagus+lemon+parmesan","Grilled Asparagus with Lemon");
addRecipe("polenta+parmesan+butter","Creamy Polenta");
addRecipe("sweet_potato+marshmallow+butter","Sweet Potato Casserole");
addRecipe("coleslaw+vinegar+carrot+cabbage","Classic Coleslaw");
addRecipe("fried_plantain+salt","Fried Plantains");
addRecipe("flour+butter+sugar+apple","Apple Tart");
addRecipe("chocolate+butter+sugar+flour","Chocolate Brownies");
addRecipe("cream+fruit+sugar+gelatin","Fruit Panna Cotta");
addRecipe("egg+cream+sugar+vanilla","Vanilla Custard");
addRecipe("flour+butter+sugar+lemon","Lemon Bars");
addRecipe("milk+rice+sugar+vanilla","Rice Pudding");
addRecipe("cream+chocolate+sugar+egg","Chocolate Mousse");
addRecipe("dough+fruit+sugar","Fruit Turnover");
addRecipe("flour+butter+sugar+almond","Almond Cookies");
addRecipe("cream+fruit+honey","Honey Fruit Salad");
addRecipe("tomato+vinegar+sugar+salt","Homemade Ketchup");
addRecipe("olive_oil+garlic+basil+parmesan","Classic Pesto");
addRecipe("yogurt+cucumber+garlic+lemon","Tzatziki Sauce");
addRecipe("mayonnaise+garlic+lemon","Aioli");
addRecipe("soy_sauce+ginger+honey","Teriyaki Sauce");
addRecipe("vinegar+oil+mustard+garlic","Vinaigrette Dressing");
addRecipe("tomato+chipotle+lime","Chipotle Salsa");
addRecipe("pepper+cream+stock","Peppercorn Sauce");
addRecipe("butter+garlic+parsley","Garlic Butter");
addRecipe("butter+cream+lemon","Lemon Butter Sauce");
addRecipe("flour+butter+sugar+cinnamon","Cinnamon Rolls");
addRecipe("flour+butter+sugar+blueberry","Blueberry Muffins");
addRecipe("flour+egg+milk+sugar+blueberry","Blueberry Pancakes");
addRecipe("flour+butter+sugar+chocolate","Chocolate Chip Cookies");
addRecipe("dough+tomato_sauce+cheese","Margherita Pizza (handheld)");
addRecipe("dough+cheese+spinach+ricotta","Spinach Ricotta Calzone");
addRecipe("dough+tomato+mozzarella+basil","Neapolitan Pizza");
addRecipe("batter+chocolate+sugar","Chocolate Cake");
addRecipe("batter+vanilla+sugar","Vanilla Cake");
addRecipe("batter+lemon+sugar","Lemon Drizzle Cake");
addRecipe("coffee+milk+sugar","Caf\u00e9 au Lait");
addRecipe("coffee+espresso+milk","Cappuccino");
addRecipe("tea+lemon+honey","Hot Lemon Tea");
addRecipe("milk+banana+honey+ice","Banana Smoothie");
addRecipe("orange_juice+ice","Fresh Orange Juice");
addRecipe("water+lemon+mint+ice","Citrus Mint Water");
addRecipe("milk+chocolate_powder+sugar","Chocolate Milkshake");
addRecipe("coffee+milk+ice+cream","Affogato");
addRecipe("milk+coffee+chocolate","Mocha");
addRecipe("tea+milk+sugar+ice","Iced Milk Tea");
addRecipe("bread+peanut_butter+honey","Peanut Butter & Honey Sandwich");
addRecipe("bread+almond_butter+jam","Almond Butter & Jam Sandwich");
addRecipe("tortilla+shrimp+avocado+salsa","Shrimp & Avocado Taco");
addRecipe("rice+cilantro+lime+avocado","Cilantro Lime Rice with Avocado");
addRecipe("pasta+clam+garlic+white_wine","Clam Linguine");
addRecipe("pasta+pesto+cherry_tomato+mozzarella","Pesto Pasta with Cherry Tomatoes");
addRecipe("rice+beef+soy_sauce+ginger","Beef Teriyaki Rice");
addRecipe("noodles+sesame_oil+soy_sauce+scallion","Scallion Sesame Noodles");
addRecipe("bread+smoked_salmon+cream_cheese+capers","Bagel Lox Deluxe");
addRecipe("rice+vinegar+sugar+seaweed+salmon","Salmon Sushi Roll");
addRecipe("potato+egg+yogurt+chive","Potato Salad with Chive Yogurt");
addRecipe("potato+cheddar+broccoli","Broccoli Cheddar Potato Bake");
addRecipe("rice+shrimp+peas+saffron","Seafood Paella");
addRecipe("dough+ham+cheese+egg","Breakfast Calzone");
addRecipe("bread+grilled_vegetable+mozzarella","Grilled Veggie Sandwich");
addRecipe("bread+fried_egg+bacon+cheddar","Classic Breakfast Sandwich");
addRecipe("pasta+vodka_sauce+cream+tomato","Penne alla Vodka");
addRecipe("meat+potato+carrot+peas","Classic Pot Roast");
addRecipe("egg+flour+sugar+butter+lemon","Lemon Sponge Cake");
addRecipe("flour+butter+garlic+parsley","Herb Garlic Knots");
addRecipe("chickpea+tomato+cumin+garlic","Chana Masala");
addRecipe("lamb+garlic+mint+yogurt","Lamb Kofta with Yogurt");
addRecipe("eggplant+tomato+garlic+parsley","Baba Ganoush-ish Roast");
addRecipe("flatbread+hummus+tabbouleh","Hummus & Tabbouleh Plate");
addRecipe("yogurt+cucumber+garlic+mint","Raita");
addRecipe("rice+chicken+saffron+pepper","Chicken Biryani");
addRecipe("lentil+rice+spice","Mujadara");
addRecipe("bulgur+tomato+parsley+lemon","Tabbouleh Salad");
addRecipe("pita+falafel+lettuce+tomato","Falafel Pita");
addRecipe("yogurt+garlic+lemon+salt","Yogurt Dip");
addRecipe("chicken+tomato+garam_masala+cream","Butter Chicken");
addRecipe("potato+pea+curry_powder+tomato","Aloo Matar");
addRecipe("spinach+paneer+tomato+garam_masala","Palak Paneer");
addRecipe("dough+potato+peas+spice","Samosa");
addRecipe("lentil+turmeric+garlic","Dal Tadka");
addRecipe("rice+chicken+cardamom+clove","Biryani Variation");
addRecipe("bread+butter+garlic+ginger","Garlic Naan-ish");
addRecipe("chickpea+coconut_milk+spinach","Coconut Chickpea Curry");
addRecipe("eggplant+potato+tomato+spice","Baingan Bharta");
addRecipe("paneer+tomato+cream+spices","Paneer Masala");
addRecipe("noodles+soy_sauce+egg+bean_sprout","Pad Thai-like Noodles");
addRecipe("rice+fish_sauce+lime+sugar","Thai-style Rice");
addRecipe("coconut_milk+lemongrass+chicken+galangal","Thai Coconut Soup");
addRecipe("rice+vinegar+soy+ginger+wasabi","Sushi Platter");
addRecipe("rice+vinegar+soy+ginger+sliced_fish","Sashimi-style Plate");
addRecipe("noodles+peanut+tofu+green_onion","Indonesian Peanut Noodles");
addRecipe("noodles+chili_oil+garlic+peanut","Dan Dan Noodles-ish");
addRecipe("pork+ginger+scallion+soy","Chinese Stir-fry Pork");
addRecipe("tofu+black_bean_sauce+garlic","Tofu in Black Bean Sauce");
addRecipe("rice+fish+seaweed+soy","Onigiri Variants");
addRecipe("cabbage+meat+tomato+sour_cream","Cabbage Roll Stew");
addRecipe("beet+horseradish+vinegar","Beet Salad");
addRecipe("potato+onion+flour+egg","Draniki (Potato Pancakes)");
addRecipe("dough+meat+onion","Pirozhki");
addRecipe("sour_cream+herb+cucumber","Sour Cream Cucumber Salad");
addRecipe("rye_bread+smoked_fish+butter","Smoked Fish on Rye");
addRecipe("buckwheat+butter+mushroom","Buckwheat with Mushrooms");
addRecipe("sour_cream+beet+walnut","Beet Salad with Sour Cream");
addRecipe("dumpling+dough+meat","Pelmeni-like Dumplings");
addRecipe("stew+beef+potato+carrot","Hearty Russian Stew");
addRecipe("potato+cream+cheese+onion","Potato Dauphinoise");
addRecipe("mushroom+cream+white_wine","Mushroom Fricassee");
addRecipe("onion+beef+gravy+bread","French Onion Soup with Beef");
addRecipe("fish+cream+herb+lemon","Fish \u00e0 la Meuni\u00e8re");
addRecipe("egg+pancake_flour+apple","German Apple Pancake");
addRecipe("sausage+potato+mustard","Bangers & Mash-style Plate");
addRecipe("veal+lemon+capers","Piccata-style Veal");
addRecipe("rice+sausage+pepper+tomato","Jambalaya-ish");
addRecipe("potato+flour+egg+cheese","Gnocchi Variants");
addRecipe("beef+mustard+cream","Beef Stroganoff");
addRecipe("corn_tortilla+cheese+beans","Quesadilla");
addRecipe("cornmeal+cheese+egg","Arepa with Cheese");
addRecipe("rice+beans+plantain+salad","Latin Rice & Beans Plate");
addRecipe("beef+corn_tortilla+onion+cilantro","Carne Asada Street Taco");
addRecipe("cornmeal+meat+cheese","Empanada-like Pocket");
addRecipe("corn+milk+sugar","Corn Pudding");
addRecipe("corn_tortilla+chicken+mole","Chicken Mole");
addRecipe("beans+olive_oil+onion+garlic","Refried Beans");
addRecipe("corn+cheese+butter","Elote-style Corn");
addRecipe("rice+steak+egg","Arroz a la Cubana");
addRecipe("oat_seed+milk+honey+banana","Banana Oat Porridge");
addRecipe("egg+smoked_salmon+cream_cheese+chive","Smoked Salmon Scrambled Eggs");
addRecipe("yogurt+honey+granola+berry","Greek Yogurt Parfait");
addRecipe("bread+butter+jam+banana","Banana & Jam Toast");
addRecipe("egg+bacon+cheddar+english_muffin","Egg & Bacon English Muffin");
addRecipe("hash_browns+egg+cheese","Breakfast Hash Bowl");
addRecipe("brioche+egg+syrup","Brioche French Toast");
addRecipe("croissant+ham+cheese","Ham & Cheese Croissant");
addRecipe("bagel+lox+cream_cheese+capers","Lox & Capers Bagel");
addRecipe("scone+clotted_cream+jam","Classic Scone with Jam");
addRecipe("brioche+pulled_pork+slaw","Pulled Pork Brioche");
addRecipe("bagel+egg+cheese+sausage","Breakfast Bagel Sandwich");
addRecipe("ciabatta+prosciutto+mozzarella+arugula","Prosciutto & Mozzarella Ciabatta");
addRecipe("bap+fish+lettuce+tartar","Fish Sandwich with Tartar");
addRecipe("bagel+cream_cheese+herb","Herbed Cream Cheese Bagel");
addRecipe("burger_patty+cheddar+onion_ring+bun","Onion Ring Burger");
addRecipe("burger_patty+blue_cheese+arugula+bun","Blue Cheese Burger");
addRecipe("veggie_patty+avocado+sprout+bun","Sprout & Avocado Veggie Burger");
addRecipe("slider_bun+pulled_beef+bbq","Beef Slider with BBQ");
addRecipe("brioche+chicken_schnitzel+slaw","Chicken Schnitzel Sandwich");
addRecipe("rice+salmon+avocado+cucumber+soy_sauce","Salmon Poke Bowl");
addRecipe("lentil+feta+tomato+olive_oil","Warm Lentil & Feta Salad");
addRecipe("farro+roasted_veg+feta+lemon","Farro Grain Bowl");
addRecipe("buckwheat+apple+cinnamon+nuts","Warm Buckwheat Breakfast Bowl");
addRecipe("barley+roasted_beet+goat_cheese","Barley & Beet Salad");
addRecipe("soba_noodles+cucumber+sesame","Cold Soba Salad");
addRecipe("bulgur+tomato+mint+lemon","Tabbouleh Variant");
addRecipe("rice+beef+broccoli+soy","Beef & Broccoli Rice Bowl");
addRecipe("lettuce+grilled_peach+burrata+prosciutto","Grilled Peach & Burrata Salad");
addRecipe("zoodle+almond_pesto+parmesan","Zucchini Noodle Pesto");
addRecipe("pasta+anchovy+garlic+crumb","Pasta with Anchovy Breadcrumbs");
addRecipe("lasagna+vegetable+ricotta+tomato","Vegetable Lasagna");
addRecipe("orzo+lemon+parsley+feta","Lemony Orzo with Feta");
addRecipe("pappardelle+beef_ragu","Pappardelle Bolognese");
addRecipe("cavatappi+sausage+peppers+tomato","Cavatappi with Sausage & Peppers");
addRecipe("baked_ziti+ricotta+mozzarella+tomato","Baked Ziti");
addRecipe("fettuccine+truffle_oil+parmesan","Truffle Fettuccine");
addRecipe("pasta+clam+chili+garlic","Spicy Clam Pasta");
addRecipe("spaghetti+meatballs+parmesan","Spaghetti & Meatballs Classic");
addRecipe("lasagna+bechamel+spinach+cheese","Spinach Lasagna");
addRecipe("arborio+parmesan+white_wine+mushroom","Mushroom Risotto");
addRecipe("rice+peas+mint+lemon","Peas & Lemon Risotto-ish");
addRecipe("risotto+pumpkin+sage+parmesan","Pumpkin Sage Risotto");
addRecipe("rice+black_beans+cilantro+lime","Cuban Black Beans & Rice");
addRecipe("rice+shrimp+saffron+peppers","Seafood Paella Variant");
addRecipe("congee+ginger+scallion","Ginger Scallion Congee");
addRecipe("risotto+seafood+cream","Seafood Risotto");
addRecipe("rice+beef+peppers+onion","Arroz con Carne");
addRecipe("rice+corn+pepper+onion","Mexican Corn Rice");
addRecipe("rice+lefse+butter+salt","Simple Buttered Rice (comfort)");
addRecipe("clam+pasta+white_wine+parsley","Clam Pasta");
addRecipe("crab+corn+cream+scallion","Crab & Corn Chowder");
addRecipe("salmon+cream_cheese+dill+bagel","Salmon & Dill Bagel");
addRecipe("tuna+olive_oil+lemon+rosemary","Tuna Steak with Herbs");
addRecipe("prawn+coconut_curry+rice","Prawn Coconut Curry");
addRecipe("fish+black_pepper+soy","Black Pepper Fish");
addRecipe("sea_bass+lime+cilantro","Citrus Sea Bass");
addRecipe("smoked_mackerel+potato+capers","Smoked Mackerel Salad");
addRecipe("octopus+chili+garlic+lemon","Spicy Octopus");
addRecipe("shrimp+corn+pepper+rice","Shrimp & Corn Risotto");
addRecipe("chicken+paprika+garlic+lemon","Paprika Roast Chicken");
addRecipe("beef+tomato+paprika+potato","Goulash-style Beef Stew");
addRecipe("pork+barbecue_rub+apple","Smoked Pulled Pork with Apple Slaw");
addRecipe("chicken+cream+mushroom+rice","Chicken & Mushroom Fricassee");
addRecipe("duck+berry_sauce","Duck with Berry Reduction");
addRecipe("meatloaf+tomato_glaze+potato","Classic Meatloaf Dinner");
addRecipe("braised_beef+beer+onion","Beer Braised Beef");
addRecipe("pork_chop+apple+sage","Pan-seared Pork Chop with Apples");
addRecipe("chicken+garlic+butter+parsley","Garlic Butter Chicken");
addRecipe("veal+crumb+lemon","Breaded Veal Cutlet");
addRecipe("tortilla+shrimp+chipotle+slaw","Chipotle Shrimp Tacos");
addRecipe("tortilla+fish+avocado+crema","Fish Tacos with Avocado Crema");
addRecipe("enchilada+cheese+chicken+sauce","Cheesy Chicken Enchiladas");
addRecipe("taco_shell+barbacoa+onion+cilantro","Barbacoa Tacos Classic");
addRecipe("tortilla+steak+onion+chimichurri","Steak Chimichurri Tacos");
addRecipe("tortilla+veggie+black_bean+avocado","Black Bean & Avocado Tacos");
addRecipe("tortilla+pulled_pork+pineapple","Pulled Pork Tacos with Pineapple");
addRecipe("tortilla+carne_asada+chimichurri","Carne Asada with Chimichurri");
addRecipe("tortilla+veggie_fajita+peppers+onion","Veggie Fajitas");
addRecipe("tortilla+queso+jalapeno+chipotle","Spicy Queso Dip & Chips");
addRecipe("olive_oil+bread+peanut_butter+jam","Grilled Bread");
addRecipe("olive_oil+bread+cheese+butter","Baked Bread");
addRecipe("rosemary+bread+bacon+lettuce+tomato+mayonnaise","Roasted Bread");
addRecipe("smoked_salt+flour+milk+egg+sugar","Smoked Flour");
addRecipe("bread+egg+milk+butter","Pan-seared Bread");
addRecipe("breaded+flour+water+yeast+salt","Crispy Flour");
addRecipe("chili+rice+chicken+broth+vegetable","Spicy Chicken");
addRecipe("honey+pasta+tomato_sauce+beef","Honey-Glazed Beef");
addRecipe("lemon+pasta+olive_oil+garlic+parmesan","Lemon Pasta");
addRecipe("thyme+potato+oil+salt","Herb Potato");
addRecipe("olive_oil+potato+butter+milk","Grilled Potato");
addRecipe("olive_oil+tomato+broth+cream","Baked Tomato");
addRecipe("rosemary+chicken+broth+vegetable","Roasted Chicken");
addRecipe("smoked_salt+fish+lemon+butter","Smoked Fish");
addRecipe("shrimp+garlic+butter","Pan-seared Shrimp");
addRecipe("breaded+tuna+mayonnaise+bread","Crispy Tuna");
addRecipe("chili+egg+mayonnaise+bread","Spicy Egg");
addRecipe("honey+lettuce+parmesan+chicken","Honey-Glazed Chicken");
addRecipe("lemon+flatbread+cheese+chicken","Lemon Chicken");
addRecipe("thyme+corn_chip+cheese+jalapeno","Herb Corn chip");
addRecipe("olive_oil+beef+potato+carrot+onion","Grilled Beef");
addRecipe("olive_oil+ground_meat+tomato_sauce+herbs","Baked Ground meat");
addRecipe("rosemary+bread+egg+cheese","Roasted Bread");
addRecipe("smoked_salt+rice+egg+soy_sauce","Smoked Rice");
addRecipe("bread+butter+garlic+parsley","Pan-seared Bread");
addRecipe("breaded+potato+cheese+bacon","Crispy Potato");
addRecipe("chili+flour+egg+milk+butter","Spicy Flour");
addRecipe("oat_seed+milk+honey","Honey-Glazed Oat seed");
addRecipe("lemon+bread+mozzarella+tomato+basil","Lemon Bread");
addRecipe("thyme+avocado+lime+salt+corn_chip","Herb Avocado");
addRecipe("olive_oil+black_bean+rice+pepper+cheese","Grilled Black bean");
addRecipe("olive_oil+lentil+carrot+onion+tomato","Baked Lentil");
addRecipe("rosemary+mushroom+cream+garlic","Roasted Mushroom");
addRecipe("smoked_salt+egg+cheese+milk","Smoked Egg");
addRecipe("butter+pasta+cream+mushroom+parmesan","Pan-seared Pasta");
addRecipe("breaded+tomato+sugar+vinegar+onion","Crispy Tomato");
addRecipe("chili+cucumber+vinegar+sugar","Spicy Cucumber");
addRecipe("honey+corn+butter+salt","Honey-Glazed Corn");
addRecipe("lemon+coconut_milk+rice+sugar","Lemon Coconut milk");
addRecipe("thyme+banana+flour+egg+sugar","Herb Banana");
addRecipe("olive_oil+apple+flour+sugar+butter","Grilled Apple");
addRecipe("olive_oil+salmon+lemon+dill","Baked Salmon");
addRecipe("rosemary+tofu+soy_sauce+ginger","Roasted Tofu");
addRecipe("smoked_salt+chickpea+garlic+lemon+olive_oil","Smoked Chickpea");
addRecipe("butter+shrimp+batter+oil","Pan-seared Shrimp");
addRecipe("breaded+rice+beans+cheese+salsa","Crispy Rice");
addRecipe("chili+bread+jam+butter","Spicy Bread");
addRecipe("honey+pasta+olive_oil+garlic+chili","Honey-Glazed Pasta");
addRecipe("lemon+sugar+milk+egg_yolk+flour","Lemon Sugar");
addRecipe("thyme+beef+onion+salt+pepper","Herb Beef");
addRecipe("olive_oil+dough+sauce+cheese","Grilled Dough");
addRecipe("olive_oil+flour+butter+sugar+egg","Baked Flour");
addRecipe("rosemary+cream+fruit+sugar","Roasted Cream");
addRecipe("smoked_salt+coffee+milk+sugar","Smoked Coffee");
addRecipe("butter+milk+ice_cream+syrup","Pan-seared Milk");
addRecipe("breaded+root_beer+ice_cream","Crispy Root beer");
addRecipe("chili+coffee+milk+ice","Spicy Coffee");
addRecipe("honey+tea+milk+sugar","Honey-Glazed Tea");
addRecipe("lemon+flour+butter+salt","Lemon Flour");
addRecipe("thyme+batter+sugar+butter","Herb Batter");
addRecipe("olive_oil+dough+tomato_sauce+cheese+pepperoni","Grilled Dough");
addRecipe("olive_oil+egg+flour+milk+sugar","Baked Egg");
addRecipe("rosemary+rice+vinegar+sugar+seaweed+fish","Roasted Rice");
addRecipe("smoked_salt+potato+egg+onion+flour","Smoked Potato");
addRecipe("butter+cornmeal+water+salt","Pan-seared Cornmeal");
addRecipe("breaded+potato+onion+egg+flour","Crispy Potato");
addRecipe("chili+bread+butter+garlic","Spicy Bread");
addRecipe("honey+mango+banana+milk","Honey-Glazed Mango");
addRecipe("lemon+chocolate+milk+sugar","Lemon Chocolate");
addRecipe("thyme+tomato+mozzarella+basil","Herb Tomato");
addRecipe("bread+olive_oil+garlic","Grilled Bread");
addRecipe("olive_oil+chicken+barbecue_sauce","Baked Chicken");
addRecipe("rosemary+pork+soy_sauce+ginger+garlic","Roasted Pork");
addRecipe("smoked_salt+beef+onion+soy_sauce","Smoked Beef");
addRecipe("egg+flour+milk+butter","Pan-seared Egg");
addRecipe("breaded+spinach+ricotta+egg+dough","Crispy Spinach");
addRecipe("chili+rice+chicken+coconut_milk","Spicy Chicken");
addRecipe("honey+noodles+peanut_butter+soy_sauce+vinegar","Honey-Glazed Noodles");
addRecipe("lemon+potato+cheese+cream","Lemon Potato");
addRecipe("thyme+beans+tomato+spice","Herb Beans");
addRecipe("olive_oil+bread+garlic+cheese","Grilled Bread");
addRecipe("olive_oil+fruit+sugar+lemon","Baked Fruit");
addRecipe("rosemary+cream+chocolate+sugar","Roasted Cream");
addRecipe("smoked_salt+chicken+lemon+butter+parsley","Smoked Chicken");
addRecipe("butter+beef+red_wine+onion+thyme","Pan-seared Beef");
addRecipe("breaded+duck+orange+sugar","Crispy Duck");
addRecipe("chili+egg+milk+sugar+vanilla","Spicy Egg");
addRecipe("honey+potato+herb+salt+oil","Honey-Glazed Potato");
addRecipe("lemon+salad_leaves+goat_cheese+beetroot+walnut","Lemon Salad leaves");
addRecipe("thyme+zucchini+tomato+garlic+olive_oil","Herb Zucchini");
addRecipe("olive_oil+rice+vinegar+sugar+egg","Grilled Rice");
addRecipe("olive_oil+bagel+cream_cheese+smoked_salmon","Baked Bagel");
addRecipe("rosemary+bagel+cream_cheese+tomato","Roasted Bagel");
addRecipe("smoked_salt+bread+avocado+egg+salt","Smoked Bread");
addRecipe("butter+tortilla+chicken+lettuce+tomato","Pan-seared Chicken");
addRecipe("breaded+tortilla+black_bean+corn+salsa","Crispy Tortilla");
addRecipe("chili+bread+roast_beef+horseradish+lettuce","Spicy Bread");
addRecipe("honey+bread+ham+cheese+mustard","Honey-Glazed Bread");
addRecipe("lemon+bread+turkey+cranberry+lettuce","Lemon Bread");
addRecipe("thyme+ciabatta+mozzarella+tomato+basil","Herb Ciabatta");
addRecipe("olive_oil+pita+hummus+grilled_veg","Grilled Pita");
addRecipe("olive_oil+naan+chicken_tikka+yogurt","Baked Naan");
addRecipe("rosemary+torta_bread+refried_bean+cheese+avocado","Roasted Torta bread");
addRecipe("smoked_salt+baguette+brie+apple","Smoked Baguette");
addRecipe("pretzel+butter+salt","Pan-seared Pretzel");
addRecipe("breaded+english_muffin+egg+cheese+ham","Crispy English muffin");
addRecipe("chili+wrap+falafel+tzatziki+lettuce","Spicy Wrap");
addRecipe("honey+lavash+smoked_salmon+cream_cheese+capers","Honey-Glazed Lavash");
addRecipe("lemon+lettuce+tomato+cucumber+olive_oil+vinegar","Lemon Lettuce");
addRecipe("thyme+spinach+strawberry+almond+goat_cheese","Herb Spinach");
addRecipe("olive_oil+kale+quinoa+chickpea+lemon","Grilled Kale");
addRecipe("olive_oil+arugula+pear+parmesan+walnut","Baked Arugula");
addRecipe("rosemary+tomato+mozzarella+basil+olive_oil","Roasted Tomato");
addRecipe("smoked_salt+cucumber+yogurt+dill","Smoked Cucumber");
addRecipe("butter+corn+black_bean+tomato+cilantro","Pan-seared Corn");
addRecipe("breaded+lettuce+avocado+shrimp+citrus_dressing","Crispy Shrimp");
addRecipe("chili+mixed_greens+goat_cheese+pear+walnuts","Spicy Mixed greens");
addRecipe("honey+couscous+mint+tomato+cucumber","Honey-Glazed Couscous");
addRecipe("lemon+tomato+crouton+cream+basil","Lemon Tomato");
addRecipe("thyme+lentil+smoked_paprika+carrot+celery","Herb Lentil");
addRecipe("olive_oil+miso+tofu+seaweed+scallion","Grilled Tofu");
addRecipe("olive_oil+broth+noodles+chicken+soy_sauce","Baked Chicken");
addRecipe("rosemary+potato+leek+cream+butter","Roasted Potato");
addRecipe("smoked_salt+beef+barley+carrot+celery","Smoked Beef");
addRecipe("butter+clam+potato+cream+celery","Pan-seared Clam");
addRecipe("breaded+tomato+red_lentil+cumin","Crispy Tomato");
addRecipe("chili+carrot+ginger+cream","Spicy Carrot");
addRecipe("honey+pumpkin+cream+nutmeg","Honey-Glazed Pumpkin");
addRecipe("lemon+pasta+carbonara_sauce+egg_yolk+parmesan+pepper","Lemon Pasta");
addRecipe("thyme+lasagna_noodle+ground_beef+ricotta+tomato_sauce+mozzarella","Herb Lasagna noodle");
addRecipe("olive_oil+penne+arrabbiata_sauce+chili","Grilled Penne");
addRecipe("olive_oil+gnocchi+tomato_sauce+mozzarella","Baked Gnocchi");
addRecipe("rosemary+ravioli+ricotta+spinach+butter_sage","Roasted Ravioli");
addRecipe("smoked_salt+tagliatelle+wild_mushroom+cream","Smoked Tagliatelle");
addRecipe("butter+bucatini+amatriciana_sauce+guanciale","Pan-seared Bucatini");
addRecipe("breaded+pasta+pesto+pine_nuts+parmesan","Crispy Pasta");
addRecipe("chili+spaghetti+clams+white_wine+garlic","Spicy Spaghetti");
addRecipe("honey+macaroni+cheddar+milk+butter","Honey-Glazed Macaroni");
addRecipe("lemon+rice+soy_sauce+egg+scallion","Lemon Rice");
addRecipe("thyme+rice+vinegar+sugar+seaweed+raw_fish","Herb Rice");
addRecipe("olive_oil+rice+vinegar+sugar+seaweed+avocado+crab","Grilled Rice");
addRecipe("olive_oil+rice+coconut_milk+banana","Baked Rice");
addRecipe("rosemary+rice+turmeric+chicken+saffron","Roasted Chicken");
addRecipe("smoked_salt+noodles+peanut_sauce+cucumber+carrot","Smoked Noodles");
addRecipe("butter+rice+soy_sauce+ginger+chicken","Pan-seared Chicken");
addRecipe("breaded+rice+beans+plantain+avocado","Crispy Rice");
addRecipe("chili+quinoa+black_bean+corn+lime","Spicy Quinoa");
addRecipe("honey+noodles+char_siu+bok_choy","Honey-Glazed Noodles");
addRecipe("lemon+salmon+soy_sauce+ginger+sesame","Lemon Salmon");
addRecipe("thyme+shrimp+garlic+white_wine+butter","Herb Shrimp");
addRecipe("olive_oil+fish+cornmeal+oil+lemon","Grilled Fish");
addRecipe("olive_oil+crab+butter+garlic+parsley","Baked Crab");
addRecipe("rosemary+scallop+lemon+butter+garlic","Roasted Scallop");
addRecipe("smoked_salt+tuna+olive_oil+lemon+capers","Smoked Tuna");
addRecipe("butter+mussels+white_wine+tomato+garlic","Pan-seared Mussels");
addRecipe("breaded+octopus+potato+olive_oil+lemon","Crispy Octopus");
addRecipe("chili+salmon+maple_glaze","Spicy Salmon");
addRecipe("honey+shrimp+rice+spice","Honey-Glazed Shrimp");
addRecipe("chicken+lemon+rosemary+olive_oil","Lemon Chicken");
addRecipe("thyme+beef+red_wine+mushroom+onion","Herb Beef");
addRecipe("olive_oil+pork+soy_sauce+honey+garlic","Grilled Pork");
addRecipe("olive_oil+lamb+garlic+rosemary+wine","Baked Lamb");
addRecipe("rosemary+duck+hoisin+scallion+cucumber","Roasted Duck");
addRecipe("smoked_salt+meatball+tomato_sauce+pasta","Smoked Meatball");
addRecipe("butter+beef+black_pepper+sauce","Pan-seared Beef");
addRecipe("breaded+chicken+curry_powder+coconut_milk","Crispy Chicken");
addRecipe("chili+pork+apple+sage","Spicy Pork");
addRecipe("honey+veal+marsala+mushroom","Honey-Glazed Veal");
addRecipe("lemon+tortilla+carne_asada+onion+cilantro","Lemon Tortilla");
addRecipe("thyme+tortilla+fish+slaw+lime","Herb Tortilla");
addRecipe("olive_oil+tortilla+chicken+cheese+salsa","Grilled Chicken");
addRecipe("olive_oil+taco_shell+ground_beef+lettuce+cheese","Baked Taco shell");
addRecipe("rosemary+tortilla+vegetable+black_bean+cheese","Roasted Tortilla");
addRecipe("smoked_salt+masa+chicken+pepper_cheese","Smoked Chicken");
addRecipe("butter+enchilada_tortilla+chicken+enchilada_sauce+cheese","Pan-seared Chicken");
addRecipe("breaded+tortilla+barbacoa+onion+cilantro","Crispy Tortilla");
addRecipe("chili+tortilla+al pastor+pineapple","Spicy Tortilla");
addRecipe("honey+tortilla+chorizo+potato+egg","Honey-Glazed Tortilla");
addRecipe("lemon+potato+rosemary+olive_oil+salt","Lemon Potato");
addRecipe("thyme+green_beans+almond+butter","Herb Green beans");
addRecipe("olive_oil+brussels_sprout+bacon+maple","Grilled Brussels sprout");
addRecipe("olive_oil+corn+butter+parmesan+chili","Baked Corn");
addRecipe("rosemary+mushroom+garlic+butter","Roasted Mushroom");
addRecipe("smoked_salt+asparagus+lemon+parmesan","Smoked Asparagus");
addRecipe("polenta+parmesan+butter","Pan-seared Polenta");
addRecipe("breaded+sweet_potato+marshmallow+butter","Crispy Sweet potato");
addRecipe("chili+coleslaw+vinegar+carrot+cabbage","Spicy Coleslaw");
addRecipe("honey+fried_plantain+salt","Honey-Glazed Fried plantain");
addRecipe("lemon+flour+butter+sugar+apple","Lemon Flour");
addRecipe("thyme+chocolate+butter+sugar+flour","Herb Chocolate");
addRecipe("olive_oil+cream+fruit+sugar+gelatin","Grilled Cream");
addRecipe("olive_oil+egg+cream+sugar+vanilla","Baked Egg");
addRecipe("rosemary+flour+butter+sugar+lemon","Roasted Flour");
addRecipe("smoked_salt+milk+rice+sugar+vanilla","Smoked Milk");
addRecipe("butter+cream+chocolate+sugar+egg","Pan-seared Cream");
addRecipe("breaded+dough+fruit+sugar","Crispy Dough");
addRecipe("chili+flour+butter+sugar+almond","Spicy Flour");
addRecipe("cream+fruit+honey","Honey-Glazed Cream");
addRecipe("lemon+tomato+vinegar+sugar+salt","Lemon Tomato");
addRecipe("thyme+olive_oil+garlic+basil+parmesan","Herb Olive oil");
addRecipe("olive_oil+yogurt+cucumber+garlic+lemon","Grilled Yogurt");
addRecipe("olive_oil+mayonnaise+garlic+lemon","Baked Mayonnaise");
addRecipe("rosemary+soy_sauce+ginger+honey","Roasted Soy sauce");
addRecipe("smoked_salt+vinegar+oil+mustard+garlic","Smoked Vinegar");
addRecipe("butter+tomato+chipotle+lime","Pan-seared Tomato");
addRecipe("breaded+pepper+cream+stock","Crispy Pepper");
addRecipe("chili+butter+garlic+parsley","Spicy Butter");
addRecipe("honey+butter+cream+lemon","Honey-Glazed Butter");
addRecipe("lemon+flour+butter+sugar+cinnamon","Lemon Flour");
addRecipe("thyme+flour+butter+sugar+blueberry","Herb Flour");
addRecipe("olive_oil+flour+egg+milk+sugar+blueberry","Grilled Flour");
addRecipe("olive_oil+flour+butter+sugar+chocolate","Baked Flour");
addRecipe("rosemary+dough+tomato_sauce+cheese","Roasted Dough");
addRecipe("smoked_salt+dough+cheese+spinach+ricotta","Smoked Dough");
addRecipe("butter+dough+tomato+mozzarella+basil","Pan-seared Dough");
addRecipe("breaded+batter+chocolate+sugar","Crispy Batter");
addRecipe("chili+batter+vanilla+sugar","Spicy Batter");
addRecipe("honey+batter+lemon+sugar","Honey-Glazed Batter");
addRecipe("lemon+coffee+milk+sugar","Lemon Coffee");
addRecipe("thyme+coffee+espresso+milk","Herb Coffee");
addRecipe("olive_oil+tea+lemon+honey","Grilled Tea");
addRecipe("olive_oil+milk+banana+honey+ice","Baked Milk");
addRecipe("rosemary+orange_juice+ice","Roasted Orange juice");
addRecipe("smoked_salt+water+lemon+mint+ice","Smoked Water");
addRecipe("butter+milk+chocolate_powder+sugar","Pan-seared Milk");
addRecipe("breaded+coffee+milk+ice+cream","Crispy Coffee");
addRecipe("chili+milk+coffee+chocolate","Spicy Milk");
addRecipe("honey+tea+milk+sugar+ice","Honey-Glazed Tea");
addRecipe("lemon+bread+peanut_butter+honey","Lemon Bread");
addRecipe("thyme+bread+almond_butter+jam","Herb Bread");
addRecipe("olive_oil+tortilla+shrimp+avocado+salsa","Grilled Shrimp");
addRecipe("olive_oil+rice+cilantro+lime+avocado","Baked Rice");
addRecipe("rosemary+pasta+clam+garlic+white_wine","Roasted Pasta");
addRecipe("smoked_salt+pasta+pesto+cherry_tomato+mozzarella","Smoked Pasta");
addRecipe("butter+rice+beef+soy_sauce+ginger","Pan-seared Beef");
addRecipe("breaded+noodles+sesame_oil+soy_sauce+scallion","Crispy Noodles");
addRecipe("chili+bread+smoked_salmon+cream_cheese+capers","Spicy Bread");
addRecipe("honey+rice+vinegar+sugar+seaweed+salmon","Honey-Glazed Salmon");
addRecipe("lemon+potato+egg+yogurt+chive","Lemon Potato");
addRecipe("thyme+potato+cheddar+broccoli","Herb Potato");
addRecipe("olive_oil+rice+shrimp+peas+saffron","Grilled Shrimp");
addRecipe("olive_oil+dough+ham+cheese+egg","Baked Dough");
addRecipe("rosemary+bread+grilled_vegetable+mozzarella","Roasted Bread");
addRecipe("smoked_salt+bread+fried_egg+bacon+cheddar","Smoked Bread");
addRecipe("butter+pasta+vodka_sauce+cream+tomato","Pan-seared Pasta");
addRecipe("breaded+meat+potato+carrot+peas","Crispy Meat");
addRecipe("chili+egg+flour+sugar+butter+lemon","Spicy Egg");
addRecipe("honey+flour+butter+garlic+parsley","Honey-Glazed Flour");
addRecipe("lemon+chickpea+tomato+cumin+garlic","Lemon Chickpea");
addRecipe("thyme+lamb+garlic+mint+yogurt","Herb Lamb");
addRecipe("olive_oil+eggplant+tomato+garlic+parsley","Grilled Eggplant");
addRecipe("olive_oil+flatbread+hummus+tabbouleh","Baked Flatbread");
addRecipe("rosemary+yogurt+cucumber+garlic+mint","Roasted Yogurt");
addRecipe("smoked_salt+rice+chicken+saffron+pepper","Smoked Chicken");
addRecipe("butter+lentil+rice+spice","Pan-seared Lentil");
addRecipe("breaded+bulgur+tomato+parsley+lemon","Crispy Bulgur");
addRecipe("chili+pita+falafel+lettuce+tomato","Spicy Pita");
addRecipe("honey+yogurt+garlic+lemon+salt","Honey-Glazed Yogurt");
addRecipe("lemon+chicken+tomato+garam_masala+cream","Lemon Chicken");
addRecipe("thyme+potato+pea+curry_powder+tomato","Herb Potato");
addRecipe("olive_oil+spinach+paneer+tomato+garam_masala","Grilled Spinach");
addRecipe("olive_oil+dough+potato+peas+spice","Baked Dough");
addRecipe("rosemary+lentil+turmeric+garlic","Roasted Lentil");
addRecipe("smoked_salt+rice+chicken+cardamom+clove","Smoked Chicken");
addRecipe("bread+butter+garlic+ginger","Pan-seared Bread");
addRecipe("breaded+chickpea+coconut_milk+spinach","Crispy Chickpea");
addRecipe("chili+eggplant+potato+tomato+spice","Spicy Eggplant");
addRecipe("honey+paneer+tomato+cream+spices","Honey-Glazed Paneer");
addRecipe("lemon+noodles+soy_sauce+egg+bean_sprout","Lemon Noodles");
addRecipe("thyme+rice+fish_sauce+lime+sugar","Herb Rice");
addRecipe("olive_oil+coconut_milk+lemongrass+chicken+galangal","Grilled Chicken");
addRecipe("olive_oil+rice+vinegar+soy+ginger+wasabi","Baked Rice");
addRecipe("rosemary+rice+vinegar+soy+ginger+sliced_fish","Roasted Rice");
addRecipe("smoked_salt+noodles+peanut+tofu+green_onion","Smoked Tofu");
addRecipe("butter+noodles+chili_oil+garlic+peanut","Pan-seared Noodles");
addRecipe("breaded+pork+ginger+scallion+soy","Crispy Pork");
addRecipe("chili+tofu+black_bean_sauce+garlic","Spicy Tofu");
addRecipe("honey+rice+fish+seaweed+soy","Honey-Glazed Rice");
addRecipe("lemon+cabbage+meat+tomato+sour_cream","Lemon Cabbage");
addRecipe("thyme+beet+horseradish+vinegar","Herb Beet");
addRecipe("olive_oil+potato+onion+flour+egg","Grilled Potato");
addRecipe("olive_oil+dough+meat+onion","Baked Dough");
addRecipe("rosemary+sour_cream+herb+cucumber","Roasted Sour cream");
addRecipe("smoked_salt+rye_bread+smoked_fish+butter","Smoked Rye bread");
addRecipe("buckwheat+butter+mushroom","Pan-seared Buckwheat");
addRecipe("breaded+sour_cream+beet+walnut","Crispy Sour cream");
addRecipe("chili+dumpling+dough+meat","Spicy Dumpling");
addRecipe("honey+stew+beef+potato+carrot","Honey-Glazed Beef");
addRecipe("lemon+potato+cream+cheese+onion","Lemon Potato");
addRecipe("thyme+mushroom+cream+white_wine","Herb Mushroom");
addRecipe("olive_oil+onion+beef+gravy+bread","Grilled Beef");
addRecipe("olive_oil+fish+cream+herb+lemon","Baked Fish");
addRecipe("rosemary+egg+pancake_flour+apple","Roasted Egg");
addRecipe("smoked_salt+sausage+potato+mustard","Smoked Sausage");
addRecipe("butter+veal+lemon+capers","Pan-seared Veal");
addRecipe("breaded+rice+sausage+pepper+tomato","Crispy Rice");
addRecipe("chili+potato+flour+egg+cheese","Spicy Potato");
addRecipe("honey+beef+mustard+cream","Honey-Glazed Beef");
addRecipe("lemon+corn_tortilla+cheese+beans","Lemon Corn tortilla");
addRecipe("thyme+cornmeal+cheese+egg","Herb Cornmeal");
addRecipe("olive_oil+rice+beans+plantain+salad","Grilled Rice");
addRecipe("olive_oil+beef+corn_tortilla+onion+cilantro","Baked Beef");
addRecipe("rosemary+cornmeal+meat+cheese","Roasted Cornmeal");
addRecipe("smoked_salt+corn+milk+sugar","Smoked Corn");
addRecipe("butter+corn_tortilla+chicken+mole","Pan-seared Chicken");
addRecipe("breaded+beans+olive_oil+onion+garlic","Crispy Beans");
addRecipe("chili+corn+cheese+butter","Spicy Corn");
addRecipe("honey+rice+steak+egg","Honey-Glazed Rice");
addRecipe("lemon+oat_seed+milk+honey+banana","Lemon Oat seed");
addRecipe("thyme+egg+smoked_salmon+cream_cheese+chive","Herb Egg");
addRecipe("olive_oil+yogurt+honey+granola+berry","Grilled Yogurt");
addRecipe("olive_oil+bread+butter+jam+banana","Baked Bread");
addRecipe("rosemary+egg+bacon+cheddar+english_muffin","Roasted Egg");
addRecipe("smoked_salt+hash_browns+egg+cheese","Smoked Hash browns");
addRecipe("butter+brioche+egg+syrup","Pan-seared Brioche");
addRecipe("breaded+croissant+ham+cheese","Crispy Croissant");
addRecipe("chili+bagel+lox+cream_cheese+capers","Spicy Bagel");
addRecipe("honey+scone+clotted_cream+jam","Honey-Glazed Scone");
addRecipe("lemon+brioche+pulled_pork+slaw","Lemon Brioche");
addRecipe("thyme+bagel+egg+cheese+sausage","Herb Bagel");
addRecipe("olive_oil+ciabatta+prosciutto+mozzarella+arugula","Grilled Ciabatta");
addRecipe("olive_oil+bap+fish+lettuce+tartar","Baked Bap");
addRecipe("rosemary+bagel+cream_cheese+herb","Roasted Bagel");
addRecipe("smoked_salt+burger_patty+cheddar+onion_ring+bun","Smoked Burger patty");
addRecipe("butter+burger_patty+blue_cheese+arugula+bun","Pan-seared Burger patty");
addRecipe("breaded+veggie_patty+avocado+sprout+bun","Crispy Veggie patty");
addRecipe("chili+slider_bun+pulled_beef+bbq","Spicy Slider bun");
addRecipe("honey+brioche+chicken_schnitzel+slaw","Honey-Glazed Brioche");
addRecipe("lemon+rice+salmon+avocado+cucumber+soy_sauce","Lemon Salmon");
addRecipe("thyme+lentil+feta+tomato+olive_oil","Herb Lentil");
addRecipe("olive_oil+farro+roasted_veg+feta+lemon","Grilled Farro");
addRecipe("olive_oil+buckwheat+apple+cinnamon+nuts","Baked Buckwheat");
addRecipe("rosemary+barley+roasted_beet+goat_cheese","Roasted Barley");
addRecipe("smoked_salt+soba_noodles+cucumber+sesame","Smoked Soba noodles");
addRecipe("butter+bulgur+tomato+mint+lemon","Pan-seared Bulgur");
addRecipe("breaded+rice+beef+broccoli+soy","Crispy Beef");
addRecipe("chili+lettuce+grilled_peach+burrata+prosciutto","Spicy Lettuce");
addRecipe("honey+zoodle+almond_pesto+parmesan","Honey-Glazed Zoodle");
addRecipe("lemon+pasta+anchovy+garlic+crumb","Lemon Pasta");
addRecipe("thyme+lasagna+vegetable+ricotta+tomato","Herb Lasagna");
addRecipe("olive_oil+orzo+lemon+parsley+feta","Grilled Orzo");
addRecipe("olive_oil+pappardelle+beef_ragu","Baked Pappardelle");
addRecipe("rosemary+cavatappi+sausage+peppers+tomato","Roasted Cavatappi");
addRecipe("smoked_salt+baked_ziti+ricotta+mozzarella+tomato","Smoked Baked ziti");
addRecipe("butter+fettuccine+truffle_oil+parmesan","Pan-seared Fettuccine");
addRecipe("breaded+pasta+clam+chili+garlic","Crispy Pasta");
addRecipe("chili+spaghetti+meatballs+parmesan","Spicy Spaghetti");
addRecipe("honey+lasagna+bechamel+spinach+cheese","Honey-Glazed Lasagna");
addRecipe("lemon+arborio+parmesan+white_wine+mushroom","Lemon Arborio");
addRecipe("thyme+rice+peas+mint+lemon","Herb Rice");
addRecipe("olive_oil+risotto+pumpkin+sage+parmesan","Grilled Risotto");
addRecipe("olive_oil+rice+black_beans+cilantro+lime","Baked Rice");
addRecipe("rosemary+rice+shrimp+saffron+peppers","Roasted Shrimp");
addRecipe("smoked_salt+congee+ginger+scallion","Smoked Congee");
addRecipe("butter+risotto+seafood+cream","Pan-seared Risotto");
addRecipe("breaded+rice+beef+peppers+onion","Crispy Beef");
addRecipe("chili+rice+corn+pepper+onion","Spicy Rice");
addRecipe("honey+rice+lefse+butter+salt","Honey-Glazed Rice");
addRecipe("lemon+clam+pasta+white_wine+parsley","Lemon Clam");
addRecipe("thyme+crab+corn+cream+scallion","Herb Crab");
addRecipe("olive_oil+salmon+cream_cheese+dill+bagel","Grilled Salmon");
addRecipe("tuna+olive_oil+lemon+rosemary","Baked Tuna");
addRecipe("rosemary+prawn+coconut_curry+rice","Roasted Prawn");
addRecipe("smoked_salt+fish+black_pepper+soy","Smoked Fish");
addRecipe("butter+sea_bass+lime+cilantro","Pan-seared Sea bass");
addRecipe("breaded+smoked_mackerel+potato+capers","Crispy Smoked mackerel");
addRecipe("honey+shrimp+corn+pepper+rice","Honey-Glazed Shrimp");
addRecipe("chicken+paprika+garlic+lemon","Lemon Chicken");
addRecipe("thyme+beef+tomato+paprika+potato","Herb Beef");
addRecipe("olive_oil+pork+barbecue_rub+apple","Grilled Pork");
addRecipe("olive_oil+chicken+cream+mushroom+rice","Baked Chicken");
addRecipe("rosemary+duck+berry_sauce","Roasted Duck");
addRecipe("smoked_salt+meatloaf+tomato_glaze+potato","Smoked Meatloaf");
addRecipe("butter+braised_beef+beer+onion","Pan-seared Braised beef");
addRecipe("breaded+pork_chop+apple+sage","Crispy Pork chop");
addRecipe("chili+chicken+garlic+butter+parsley","Spicy Chicken");
addRecipe("honey+veal+crumb+lemon","Honey-Glazed Veal");
addRecipe("lemon+tortilla+shrimp+chipotle+slaw","Lemon Shrimp");
addRecipe("thyme+tortilla+fish+avocado+crema","Herb Tortilla");
addRecipe("olive_oil+enchilada+cheese+chicken+sauce","Grilled Chicken");
addRecipe("olive_oil+taco_shell+barbacoa+onion+cilantro","Baked Taco shell");
addRecipe("rosemary+tortilla+steak+onion+chimichurri","Roasted Tortilla");
addRecipe("smoked_salt+tortilla+veggie+black_bean+avocado","Smoked Tortilla");
addRecipe("butter+tortilla+pulled_pork+pineapple","Pan-seared Tortilla");
addRecipe("breaded+tortilla+carne_asada+chimichurri","Crispy Tortilla");
addRecipe("chili+tortilla+veggie_fajita+peppers+onion","Spicy Tortilla");
addRecipe("honey+tortilla+queso+jalapeno+chipotle","Honey-Glazed Tortilla");
addRecipe("lemon+olive_oil+bread+peanut_butter+jam","Lemon Olive oil");
addRecipe("thyme+olive_oil+bread+cheese+butter","Herb Olive oil");
addRecipe("olive_oil+rosemary+bread+bacon+lettuce+tomato+mayonnaise","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+flour+milk+egg+sugar","Baked Smoked salt");
addRecipe("rosemary+bread+egg+milk+butter","Roasted Bread");
addRecipe("smoked_salt+breaded+flour+water+yeast+salt","Smoked Breaded");
addRecipe("butter+chili+rice+chicken+broth+vegetable","Pan-seared Chicken");
addRecipe("breaded+honey+pasta+tomato_sauce+beef","Crispy Beef");
addRecipe("chili+lemon+pasta+olive_oil+garlic+parmesan","Spicy Lemon");
addRecipe("honey+thyme+potato+oil+salt","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+potato+butter+milk","Lemon Olive oil");
addRecipe("thyme+olive_oil+tomato+broth+cream","Herb Olive oil");
addRecipe("olive_oil+rosemary+chicken+broth+vegetable","Grilled Chicken");
addRecipe("olive_oil+smoked_salt+fish+lemon+butter","Baked Smoked salt");
addRecipe("rosemary+shrimp+garlic+butter","Roasted Shrimp");
addRecipe("smoked_salt+breaded+tuna+mayonnaise+bread","Smoked Tuna");
addRecipe("butter+chili+egg+mayonnaise+bread","Pan-seared Chili");
addRecipe("breaded+honey+lettuce+parmesan+chicken","Crispy Chicken");
addRecipe("chili+lemon+flatbread+cheese+chicken","Spicy Chicken");
addRecipe("honey+thyme+corn_chip+cheese+jalapeno","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+beef+potato+carrot+onion","Lemon Beef");
addRecipe("thyme+olive_oil+ground_meat+tomato_sauce+herbs","Herb Olive oil");
addRecipe("olive_oil+rosemary+bread+egg+cheese","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+rice+egg+soy_sauce","Baked Smoked salt");
addRecipe("rosemary+bread+butter+garlic+parsley","Roasted Bread");
addRecipe("smoked_salt+breaded+potato+cheese+bacon","Smoked Breaded");
addRecipe("chili+flour+egg+milk+butter","Pan-seared Chili");
addRecipe("breaded+oat_seed+milk+honey","Crispy Oat seed");
addRecipe("chili+lemon+bread+mozzarella+tomato+basil","Spicy Lemon");
addRecipe("honey+thyme+avocado+lime+salt+corn_chip","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+black_bean+rice+pepper+cheese","Lemon Olive oil");
addRecipe("thyme+olive_oil+lentil+carrot+onion+tomato","Herb Olive oil");
addRecipe("olive_oil+rosemary+mushroom+cream+garlic","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+egg+cheese+milk","Baked Smoked salt");
addRecipe("rosemary+butter+pasta+cream+mushroom+parmesan","Roasted Butter");
addRecipe("smoked_salt+breaded+tomato+sugar+vinegar+onion","Smoked Breaded");
addRecipe("butter+chili+cucumber+vinegar+sugar","Pan-seared Chili");
addRecipe("breaded+honey+corn+butter+salt","Crispy Honey");
addRecipe("chili+lemon+coconut_milk+rice+sugar","Spicy Lemon");
addRecipe("honey+thyme+banana+flour+egg+sugar","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+apple+flour+sugar+butter","Lemon Olive oil");
addRecipe("thyme+olive_oil+salmon+lemon+dill","Herb Salmon");
addRecipe("olive_oil+rosemary+tofu+soy_sauce+ginger","Grilled Tofu");
addRecipe("smoked_salt+chickpea+garlic+lemon+olive_oil","Baked Smoked salt");
addRecipe("rosemary+butter+shrimp+batter+oil","Roasted Shrimp");
addRecipe("smoked_salt+breaded+rice+beans+cheese+salsa","Smoked Breaded");
addRecipe("chili+bread+jam+butter","Pan-seared Chili");
addRecipe("breaded+honey+pasta+olive_oil+garlic+chili","Crispy Honey");
addRecipe("chili+lemon+sugar+milk+egg_yolk+flour","Spicy Lemon");
addRecipe("honey+thyme+beef+onion+salt+pepper","Honey-Glazed Beef");
addRecipe("lemon+olive_oil+dough+sauce+cheese","Lemon Olive oil");
addRecipe("thyme+olive_oil+flour+butter+sugar+egg","Herb Olive oil");
addRecipe("olive_oil+rosemary+cream+fruit+sugar","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+coffee+milk+sugar","Baked Smoked salt");
addRecipe("rosemary+butter+milk+ice_cream+syrup","Roasted Butter");
addRecipe("smoked_salt+breaded+root_beer+ice_cream","Smoked Breaded");
addRecipe("butter+chili+coffee+milk+ice","Pan-seared Chili");
addRecipe("breaded+honey+tea+milk+sugar","Crispy Honey");
addRecipe("chili+lemon+flour+butter+salt","Spicy Lemon");
addRecipe("honey+thyme+batter+sugar+butter","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+dough+tomato_sauce+cheese+pepperoni","Lemon Olive oil");
addRecipe("thyme+olive_oil+egg+flour+milk+sugar","Herb Olive oil");
addRecipe("olive_oil+rosemary+rice+vinegar+sugar+seaweed+fish","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+potato+egg+onion+flour","Baked Smoked salt");
addRecipe("rosemary+butter+cornmeal+water+salt","Roasted Butter");
addRecipe("smoked_salt+breaded+potato+onion+egg+flour","Smoked Breaded");
addRecipe("chili+bread+butter+garlic","Pan-seared Chili");
addRecipe("breaded+honey+mango+banana+milk","Crispy Honey");
addRecipe("chili+lemon+chocolate+milk+sugar","Spicy Lemon");
addRecipe("honey+thyme+tomato+mozzarella+basil","Honey-Glazed Thyme");
addRecipe("lemon+bread+olive_oil+garlic","Lemon Bread");
addRecipe("thyme+olive_oil+chicken+barbecue_sauce","Herb Chicken");
addRecipe("olive_oil+rosemary+pork+soy_sauce+ginger+garlic","Grilled Pork");
addRecipe("olive_oil+smoked_salt+beef+onion+soy_sauce","Baked Beef");
addRecipe("rosemary+egg+flour+milk+butter","Roasted Egg");
addRecipe("smoked_salt+breaded+spinach+ricotta+egg+dough","Smoked Breaded");
addRecipe("butter+chili+rice+chicken+coconut_milk","Pan-seared Chicken");
addRecipe("breaded+honey+noodles+peanut_butter+soy_sauce+vinegar","Crispy Honey");
addRecipe("chili+lemon+potato+cheese+cream","Spicy Lemon");
addRecipe("honey+thyme+beans+tomato+spice","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+bread+garlic+cheese","Lemon Olive oil");
addRecipe("thyme+olive_oil+fruit+sugar+lemon","Herb Olive oil");
addRecipe("olive_oil+rosemary+cream+chocolate+sugar","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+chicken+lemon+butter+parsley","Baked Chicken");
addRecipe("rosemary+butter+beef+red_wine+onion+thyme","Roasted Beef");
addRecipe("smoked_salt+breaded+duck+orange+sugar","Smoked Duck");
addRecipe("butter+chili+egg+milk+sugar+vanilla","Pan-seared Chili");
addRecipe("breaded+honey+potato+herb+salt+oil","Crispy Honey");
addRecipe("chili+lemon+salad_leaves+goat_cheese+beetroot+walnut","Spicy Lemon");
addRecipe("honey+thyme+zucchini+tomato+garlic+olive_oil","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+rice+vinegar+sugar+egg","Lemon Olive oil");
addRecipe("thyme+olive_oil+bagel+cream_cheese+smoked_salmon","Herb Olive oil");
addRecipe("olive_oil+rosemary+bagel+cream_cheese+tomato","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+bread+avocado+egg+salt","Baked Smoked salt");
addRecipe("rosemary+butter+tortilla+chicken+lettuce+tomato","Roasted Chicken");
addRecipe("smoked_salt+breaded+tortilla+black_bean+corn+salsa","Smoked Breaded");
addRecipe("butter+chili+bread+roast_beef+horseradish+lettuce","Pan-seared Chili");
addRecipe("breaded+honey+bread+ham+cheese+mustard","Crispy Honey");
addRecipe("chili+lemon+bread+turkey+cranberry+lettuce","Spicy Lemon");
addRecipe("honey+thyme+ciabatta+mozzarella+tomato+basil","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+pita+hummus+grilled_veg","Lemon Olive oil");
addRecipe("thyme+olive_oil+naan+chicken_tikka+yogurt","Herb Olive oil");
addRecipe("olive_oil+rosemary+torta_bread+refried_bean+cheese+avocado","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+baguette+brie+apple","Baked Smoked salt");
addRecipe("rosemary+pretzel+butter+salt","Roasted Pretzel");
addRecipe("smoked_salt+breaded+english_muffin+egg+cheese+ham","Smoked Breaded");
addRecipe("butter+chili+wrap+falafel+tzatziki+lettuce","Pan-seared Chili");
addRecipe("breaded+honey+lavash+smoked_salmon+cream_cheese+capers","Crispy Honey");
addRecipe("chili+lemon+lettuce+tomato+cucumber+olive_oil+vinegar","Spicy Lemon");
addRecipe("honey+thyme+spinach+strawberry+almond+goat_cheese","Honey-Glazed Thyme");
addRecipe("olive_oil+kale+quinoa+chickpea+lemon","Lemon Olive oil");
addRecipe("thyme+olive_oil+arugula+pear+parmesan+walnut","Herb Olive oil");
addRecipe("rosemary+tomato+mozzarella+basil+olive_oil","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+cucumber+yogurt+dill","Baked Smoked salt");
addRecipe("rosemary+butter+corn+black_bean+tomato+cilantro","Roasted Butter");
addRecipe("smoked_salt+breaded+lettuce+avocado+shrimp+citrus_dressing","Smoked Shrimp");
addRecipe("butter+chili+mixed_greens+goat_cheese+pear+walnuts","Pan-seared Chili");
addRecipe("breaded+honey+couscous+mint+tomato+cucumber","Crispy Honey");
addRecipe("chili+lemon+tomato+crouton+cream+basil","Spicy Lemon");
addRecipe("honey+thyme+lentil+smoked_paprika+carrot+celery","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+miso+tofu+seaweed+scallion","Lemon Tofu");
addRecipe("thyme+olive_oil+broth+noodles+chicken+soy_sauce","Herb Chicken");
addRecipe("olive_oil+rosemary+potato+leek+cream+butter","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+beef+barley+carrot+celery","Baked Beef");
addRecipe("rosemary+butter+clam+potato+cream+celery","Roasted Butter");
addRecipe("smoked_salt+breaded+tomato+red_lentil+cumin","Smoked Breaded");
addRecipe("butter+chili+carrot+ginger+cream","Pan-seared Chili");
addRecipe("breaded+honey+pumpkin+cream+nutmeg","Crispy Honey");
addRecipe("chili+lemon+pasta+carbonara_sauce+egg_yolk+parmesan+pepper","Spicy Lemon");
addRecipe("honey+thyme+lasagna_noodle+ground_beef+ricotta+tomato_sauce+mozzarella","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+penne+arrabbiata_sauce+chili","Lemon Olive oil");
addRecipe("thyme+olive_oil+gnocchi+tomato_sauce+mozzarella","Herb Olive oil");
addRecipe("olive_oil+rosemary+ravioli+ricotta+spinach+butter_sage","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+tagliatelle+wild_mushroom+cream","Baked Smoked salt");
addRecipe("rosemary+butter+bucatini+amatriciana_sauce+guanciale","Roasted Butter");
addRecipe("smoked_salt+breaded+pasta+pesto+pine_nuts+parmesan","Smoked Breaded");
addRecipe("butter+chili+spaghetti+clams+white_wine+garlic","Pan-seared Chili");
addRecipe("breaded+honey+macaroni+cheddar+milk+butter","Crispy Honey");
addRecipe("chili+lemon+rice+soy_sauce+egg+scallion","Spicy Lemon");
addRecipe("honey+thyme+rice+vinegar+sugar+seaweed+raw_fish","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+rice+vinegar+sugar+seaweed+avocado+crab","Lemon Olive oil");
addRecipe("thyme+olive_oil+rice+coconut_milk+banana","Herb Olive oil");
addRecipe("olive_oil+rosemary+rice+turmeric+chicken+saffron","Grilled Chicken");
addRecipe("olive_oil+smoked_salt+noodles+peanut_sauce+cucumber+carrot","Baked Smoked salt");
addRecipe("rosemary+butter+rice+soy_sauce+ginger+chicken","Roasted Chicken");
addRecipe("smoked_salt+breaded+rice+beans+plantain+avocado","Smoked Breaded");
addRecipe("butter+chili+quinoa+black_bean+corn+lime","Pan-seared Chili");
addRecipe("breaded+honey+noodles+char_siu+bok_choy","Crispy Honey");
addRecipe("chili+lemon+salmon+soy_sauce+ginger+sesame","Spicy Salmon");
addRecipe("honey+thyme+shrimp+garlic+white_wine+butter","Honey-Glazed Shrimp");
addRecipe("olive_oil+fish+cornmeal+oil+lemon","Lemon Olive oil");
addRecipe("thyme+olive_oil+crab+butter+garlic+parsley","Herb Olive oil");
addRecipe("olive_oil+rosemary+scallop+lemon+butter+garlic","Grilled Rosemary");
addRecipe("smoked_salt+tuna+olive_oil+lemon+capers","Baked Tuna");
addRecipe("rosemary+butter+mussels+white_wine+tomato+garlic","Roasted Butter");
addRecipe("smoked_salt+breaded+octopus+potato+olive_oil+lemon","Smoked Breaded");
addRecipe("butter+chili+salmon+maple_glaze","Pan-seared Salmon");
addRecipe("breaded+honey+shrimp+rice+spice","Crispy Shrimp");
addRecipe("chili+chicken+lemon+rosemary+olive_oil","Spicy Chicken");
addRecipe("honey+thyme+beef+red_wine+mushroom+onion","Honey-Glazed Beef");
addRecipe("lemon+olive_oil+pork+soy_sauce+honey+garlic","Lemon Pork");
addRecipe("thyme+olive_oil+lamb+garlic+rosemary+wine","Herb Lamb");
addRecipe("olive_oil+rosemary+duck+hoisin+scallion+cucumber","Grilled Duck");
addRecipe("olive_oil+smoked_salt+meatball+tomato_sauce+pasta","Baked Smoked salt");
addRecipe("rosemary+butter+beef+black_pepper+sauce","Roasted Beef");
addRecipe("smoked_salt+breaded+chicken+curry_powder+coconut_milk","Smoked Chicken");
addRecipe("butter+chili+pork+apple+sage","Pan-seared Pork");
addRecipe("breaded+honey+veal+marsala+mushroom","Crispy Honey");
addRecipe("chili+lemon+tortilla+carne_asada+onion+cilantro","Spicy Lemon");
addRecipe("honey+thyme+tortilla+fish+slaw+lime","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+tortilla+chicken+cheese+salsa","Lemon Chicken");
addRecipe("thyme+olive_oil+taco_shell+ground_beef+lettuce+cheese","Herb Olive oil");
addRecipe("olive_oil+rosemary+tortilla+vegetable+black_bean+cheese","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+masa+chicken+pepper_cheese","Baked Chicken");
addRecipe("rosemary+butter+enchilada_tortilla+chicken+enchilada_sauce+cheese","Roasted Chicken");
addRecipe("smoked_salt+breaded+tortilla+barbacoa+onion+cilantro","Smoked Breaded");
addRecipe("butter+chili+tortilla+al pastor+pineapple","Pan-seared Chili");
addRecipe("breaded+honey+tortilla+chorizo+potato+egg","Crispy Honey");
addRecipe("chili+lemon+potato+rosemary+olive_oil+salt","Spicy Lemon");
addRecipe("honey+thyme+green_beans+almond+butter","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+brussels_sprout+bacon+maple","Lemon Olive oil");
addRecipe("thyme+olive_oil+corn+butter+parmesan+chili","Herb Olive oil");
addRecipe("olive_oil+rosemary+mushroom+garlic+butter","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+asparagus+lemon+parmesan","Baked Smoked salt");
addRecipe("rosemary+polenta+parmesan+butter","Roasted Polenta");
addRecipe("smoked_salt+breaded+sweet_potato+marshmallow+butter","Smoked Breaded");
addRecipe("butter+chili+coleslaw+vinegar+carrot+cabbage","Pan-seared Chili");
addRecipe("breaded+honey+fried_plantain+salt","Crispy Honey");
addRecipe("chili+lemon+flour+butter+sugar+apple","Spicy Lemon");
addRecipe("honey+thyme+chocolate+butter+sugar+flour","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+cream+fruit+sugar+gelatin","Lemon Olive oil");
addRecipe("thyme+olive_oil+egg+cream+sugar+vanilla","Herb Olive oil");
addRecipe("olive_oil+rosemary+flour+butter+sugar+lemon","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+milk+rice+sugar+vanilla","Baked Smoked salt");
addRecipe("rosemary+butter+cream+chocolate+sugar+egg","Roasted Butter");
addRecipe("smoked_salt+breaded+dough+fruit+sugar","Smoked Breaded");
addRecipe("chili+flour+butter+sugar+almond","Pan-seared Chili");
addRecipe("breaded+cream+fruit+honey","Crispy Cream");
addRecipe("chili+lemon+tomato+vinegar+sugar+salt","Spicy Lemon");
addRecipe("honey+thyme+olive_oil+garlic+basil+parmesan","Honey-Glazed Thyme");
addRecipe("olive_oil+yogurt+cucumber+garlic+lemon","Lemon Olive oil");
addRecipe("thyme+olive_oil+mayonnaise+garlic+lemon","Herb Olive oil");
addRecipe("olive_oil+rosemary+soy_sauce+ginger+honey","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+vinegar+oil+mustard+garlic","Baked Smoked salt");
addRecipe("rosemary+butter+tomato+chipotle+lime","Roasted Butter");
addRecipe("smoked_salt+breaded+pepper+cream+stock","Smoked Breaded");
addRecipe("chili+butter+garlic+parsley","Pan-seared Chili");
addRecipe("breaded+honey+butter+cream+lemon","Crispy Honey");
addRecipe("chili+lemon+flour+butter+sugar+cinnamon","Spicy Lemon");
addRecipe("honey+thyme+flour+butter+sugar+blueberry","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+flour+egg+milk+sugar+blueberry","Lemon Olive oil");
addRecipe("thyme+olive_oil+flour+butter+sugar+chocolate","Herb Olive oil");
addRecipe("olive_oil+rosemary+dough+tomato_sauce+cheese","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+dough+cheese+spinach+ricotta","Baked Smoked salt");
addRecipe("rosemary+butter+dough+tomato+mozzarella+basil","Roasted Butter");
addRecipe("smoked_salt+breaded+batter+chocolate+sugar","Smoked Breaded");
addRecipe("butter+chili+batter+vanilla+sugar","Pan-seared Chili");
addRecipe("breaded+honey+batter+lemon+sugar","Crispy Honey");
addRecipe("chili+lemon+coffee+milk+sugar","Spicy Lemon");
addRecipe("honey+thyme+coffee+espresso+milk","Honey-Glazed Thyme");
addRecipe("olive_oil+tea+lemon+honey","Lemon Olive oil");
addRecipe("thyme+olive_oil+milk+banana+honey+ice","Herb Olive oil");
addRecipe("olive_oil+rosemary+orange_juice+ice","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+water+lemon+mint+ice","Baked Smoked salt");
addRecipe("rosemary+butter+milk+chocolate_powder+sugar","Roasted Butter");
addRecipe("smoked_salt+breaded+coffee+milk+ice+cream","Smoked Breaded");
addRecipe("butter+chili+milk+coffee+chocolate","Pan-seared Chili");
addRecipe("breaded+honey+tea+milk+sugar+ice","Crispy Honey");
addRecipe("chili+lemon+bread+peanut_butter+honey","Spicy Lemon");
addRecipe("honey+thyme+bread+almond_butter+jam","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+tortilla+shrimp+avocado+salsa","Lemon Shrimp");
addRecipe("thyme+olive_oil+rice+cilantro+lime+avocado","Herb Olive oil");
addRecipe("olive_oil+rosemary+pasta+clam+garlic+white_wine","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+pasta+pesto+cherry_tomato+mozzarella","Baked Smoked salt");
addRecipe("rosemary+butter+rice+beef+soy_sauce+ginger","Roasted Beef");
addRecipe("smoked_salt+breaded+noodles+sesame_oil+soy_sauce+scallion","Smoked Breaded");
addRecipe("butter+chili+bread+smoked_salmon+cream_cheese+capers","Pan-seared Chili");
addRecipe("breaded+honey+rice+vinegar+sugar+seaweed+salmon","Crispy Salmon");
addRecipe("chili+lemon+potato+egg+yogurt+chive","Spicy Lemon");
addRecipe("honey+thyme+potato+cheddar+broccoli","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+rice+shrimp+peas+saffron","Lemon Shrimp");
addRecipe("thyme+olive_oil+dough+ham+cheese+egg","Herb Olive oil");
addRecipe("olive_oil+rosemary+bread+grilled_vegetable+mozzarella","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+bread+fried_egg+bacon+cheddar","Baked Smoked salt");
addRecipe("rosemary+butter+pasta+vodka_sauce+cream+tomato","Roasted Butter");
addRecipe("smoked_salt+breaded+meat+potato+carrot+peas","Smoked Breaded");
addRecipe("chili+egg+flour+sugar+butter+lemon","Pan-seared Chili");
addRecipe("breaded+honey+flour+butter+garlic+parsley","Crispy Honey");
addRecipe("chili+lemon+chickpea+tomato+cumin+garlic","Spicy Lemon");
addRecipe("honey+thyme+lamb+garlic+mint+yogurt","Honey-Glazed Lamb");
addRecipe("lemon+olive_oil+eggplant+tomato+garlic+parsley","Lemon Olive oil");
addRecipe("thyme+olive_oil+flatbread+hummus+tabbouleh","Herb Olive oil");
addRecipe("olive_oil+rosemary+yogurt+cucumber+garlic+mint","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+rice+chicken+saffron+pepper","Baked Chicken");
addRecipe("rosemary+butter+lentil+rice+spice","Roasted Butter");
addRecipe("smoked_salt+breaded+bulgur+tomato+parsley+lemon","Smoked Breaded");
addRecipe("butter+chili+pita+falafel+lettuce+tomato","Pan-seared Chili");
addRecipe("breaded+honey+yogurt+garlic+lemon+salt","Crispy Honey");
addRecipe("chili+lemon+chicken+tomato+garam_masala+cream","Spicy Chicken");
addRecipe("honey+thyme+potato+pea+curry_powder+tomato","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+spinach+paneer+tomato+garam_masala","Lemon Olive oil");
addRecipe("thyme+olive_oil+dough+potato+peas+spice","Herb Olive oil");
addRecipe("olive_oil+rosemary+lentil+turmeric+garlic","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+rice+chicken+cardamom+clove","Baked Chicken");
addRecipe("rosemary+bread+butter+garlic+ginger","Roasted Bread");
addRecipe("smoked_salt+breaded+chickpea+coconut_milk+spinach","Smoked Breaded");
addRecipe("butter+chili+eggplant+potato+tomato+spice","Pan-seared Chili");
addRecipe("breaded+honey+paneer+tomato+cream+spices","Crispy Honey");
addRecipe("chili+lemon+noodles+soy_sauce+egg+bean_sprout","Spicy Lemon");
addRecipe("honey+thyme+rice+fish_sauce+lime+sugar","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+coconut_milk+lemongrass+chicken+galangal","Lemon Chicken");
addRecipe("thyme+olive_oil+rice+vinegar+soy+ginger+wasabi","Herb Olive oil");
addRecipe("olive_oil+rosemary+rice+vinegar+soy+ginger+sliced_fish","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+noodles+peanut+tofu+green_onion","Baked Tofu");
addRecipe("rosemary+butter+noodles+chili_oil+garlic+peanut","Roasted Butter");
addRecipe("smoked_salt+breaded+pork+ginger+scallion+soy","Smoked Pork");
addRecipe("butter+chili+tofu+black_bean_sauce+garlic","Pan-seared Tofu");
addRecipe("breaded+honey+rice+fish+seaweed+soy","Crispy Honey");
addRecipe("chili+lemon+cabbage+meat+tomato+sour_cream","Spicy Lemon");
addRecipe("honey+thyme+beet+horseradish+vinegar","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+potato+onion+flour+egg","Lemon Olive oil");
addRecipe("thyme+olive_oil+dough+meat+onion","Herb Olive oil");
addRecipe("olive_oil+rosemary+sour_cream+herb+cucumber","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+rye_bread+smoked_fish+butter","Baked Smoked salt");
addRecipe("rosemary+buckwheat+butter+mushroom","Roasted Buckwheat");
addRecipe("smoked_salt+breaded+sour_cream+beet+walnut","Smoked Breaded");
addRecipe("butter+chili+dumpling+dough+meat","Pan-seared Chili");
addRecipe("breaded+honey+stew+beef+potato+carrot","Crispy Beef");
addRecipe("chili+lemon+potato+cream+cheese+onion","Spicy Lemon");
addRecipe("honey+thyme+mushroom+cream+white_wine","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+onion+beef+gravy+bread","Lemon Beef");
addRecipe("thyme+olive_oil+fish+cream+herb+lemon","Herb Olive oil");
addRecipe("olive_oil+rosemary+egg+pancake_flour+apple","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+sausage+potato+mustard","Baked Smoked salt");
addRecipe("rosemary+butter+veal+lemon+capers","Roasted Butter");
addRecipe("smoked_salt+breaded+rice+sausage+pepper+tomato","Smoked Breaded");
addRecipe("butter+chili+potato+flour+egg+cheese","Pan-seared Chili");
addRecipe("breaded+honey+beef+mustard+cream","Crispy Beef");
addRecipe("chili+lemon+corn_tortilla+cheese+beans","Spicy Lemon");
addRecipe("honey+thyme+cornmeal+cheese+egg","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+rice+beans+plantain+salad","Lemon Olive oil");
addRecipe("thyme+olive_oil+beef+corn_tortilla+onion+cilantro","Herb Beef");
addRecipe("olive_oil+rosemary+cornmeal+meat+cheese","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+corn+milk+sugar","Baked Smoked salt");
addRecipe("rosemary+butter+corn_tortilla+chicken+mole","Roasted Chicken");
addRecipe("smoked_salt+breaded+beans+olive_oil+onion+garlic","Smoked Breaded");
addRecipe("chili+corn+cheese+butter","Pan-seared Chili");
addRecipe("breaded+honey+rice+steak+egg","Crispy Honey");
addRecipe("chili+lemon+oat_seed+milk+honey+banana","Spicy Lemon");
addRecipe("honey+thyme+egg+smoked_salmon+cream_cheese+chive","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+yogurt+honey+granola+berry","Lemon Olive oil");
addRecipe("thyme+olive_oil+bread+butter+jam+banana","Herb Olive oil");
addRecipe("olive_oil+rosemary+egg+bacon+cheddar+english_muffin","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+hash_browns+egg+cheese","Baked Smoked salt");
addRecipe("rosemary+butter+brioche+egg+syrup","Roasted Butter");
addRecipe("smoked_salt+breaded+croissant+ham+cheese","Smoked Breaded");
addRecipe("butter+chili+bagel+lox+cream_cheese+capers","Pan-seared Chili");
addRecipe("breaded+honey+scone+clotted_cream+jam","Crispy Honey");
addRecipe("chili+lemon+brioche+pulled_pork+slaw","Spicy Lemon");
addRecipe("honey+thyme+bagel+egg+cheese+sausage","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+ciabatta+prosciutto+mozzarella+arugula","Lemon Olive oil");
addRecipe("thyme+olive_oil+bap+fish+lettuce+tartar","Herb Olive oil");
addRecipe("olive_oil+rosemary+bagel+cream_cheese+herb","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+burger_patty+cheddar+onion_ring+bun","Baked Smoked salt");
addRecipe("rosemary+butter+burger_patty+blue_cheese+arugula+bun","Roasted Butter");
addRecipe("smoked_salt+breaded+veggie_patty+avocado+sprout+bun","Smoked Breaded");
addRecipe("butter+chili+slider_bun+pulled_beef+bbq","Pan-seared Chili");
addRecipe("breaded+honey+brioche+chicken_schnitzel+slaw","Crispy Honey");
addRecipe("chili+lemon+rice+salmon+avocado+cucumber+soy_sauce","Spicy Salmon");
addRecipe("honey+thyme+lentil+feta+tomato+olive_oil","Honey-Glazed Thyme");
addRecipe("olive_oil+farro+roasted_veg+feta+lemon","Lemon Olive oil");
addRecipe("thyme+olive_oil+buckwheat+apple+cinnamon+nuts","Herb Olive oil");
addRecipe("olive_oil+rosemary+barley+roasted_beet+goat_cheese","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+soba_noodles+cucumber+sesame","Baked Smoked salt");
addRecipe("rosemary+butter+bulgur+tomato+mint+lemon","Roasted Butter");
addRecipe("smoked_salt+breaded+rice+beef+broccoli+soy","Smoked Beef");
addRecipe("butter+chili+lettuce+grilled_peach+burrata+prosciutto","Pan-seared Chili");
addRecipe("breaded+honey+zoodle+almond_pesto+parmesan","Crispy Honey");
addRecipe("chili+lemon+pasta+anchovy+garlic+crumb","Spicy Lemon");
addRecipe("honey+thyme+lasagna+vegetable+ricotta+tomato","Honey-Glazed Thyme");
addRecipe("olive_oil+orzo+lemon+parsley+feta","Lemon Olive oil");
addRecipe("thyme+olive_oil+pappardelle+beef_ragu","Herb Olive oil");
addRecipe("olive_oil+rosemary+cavatappi+sausage+peppers+tomato","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+baked_ziti+ricotta+mozzarella+tomato","Baked Smoked salt");
addRecipe("rosemary+butter+fettuccine+truffle_oil+parmesan","Roasted Butter");
addRecipe("smoked_salt+breaded+pasta+clam+chili+garlic","Smoked Breaded");
addRecipe("butter+chili+spaghetti+meatballs+parmesan","Pan-seared Chili");
addRecipe("breaded+honey+lasagna+bechamel+spinach+cheese","Crispy Honey");
addRecipe("chili+lemon+arborio+parmesan+white_wine+mushroom","Spicy Lemon");
addRecipe("honey+thyme+rice+peas+mint+lemon","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+risotto+pumpkin+sage+parmesan","Lemon Olive oil");
addRecipe("thyme+olive_oil+rice+black_beans+cilantro+lime","Herb Olive oil");
addRecipe("olive_oil+rosemary+rice+shrimp+saffron+peppers","Grilled Shrimp");
addRecipe("olive_oil+smoked_salt+congee+ginger+scallion","Baked Smoked salt");
addRecipe("rosemary+butter+risotto+seafood+cream","Roasted Butter");
addRecipe("smoked_salt+breaded+rice+beef+peppers+onion","Smoked Beef");
addRecipe("butter+chili+rice+corn+pepper+onion","Pan-seared Chili");
addRecipe("breaded+honey+rice+lefse+butter+salt","Crispy Honey");
addRecipe("chili+lemon+clam+pasta+white_wine+parsley","Spicy Lemon");
addRecipe("honey+thyme+crab+corn+cream+scallion","Honey-Glazed Thyme");
addRecipe("lemon+olive_oil+salmon+cream_cheese+dill+bagel","Lemon Salmon");
addRecipe("thyme+tuna+olive_oil+lemon+rosemary","Herb Tuna");
addRecipe("olive_oil+rosemary+prawn+coconut_curry+rice","Grilled Rosemary");
addRecipe("olive_oil+smoked_salt+fish+black_pepper+soy","Baked Smoked salt");
addRecipe("rosemary+butter+sea_bass+lime+cilantro","Roasted Butter");
addRecipe("smoked_salt+breaded+smoked_mackerel+potato+capers","Smoked Breaded");
addRecipe("butter+honey+shrimp+corn+pepper+rice","Pan-seared Shrimp");
addRecipe("breaded+chicken+paprika+garlic+lemon","Crispy Chicken");
addRecipe("chili+thyme+beef+tomato+paprika+potato","Spicy Beef");
addRecipe("honey+olive_oil+pork+barbecue_rub+apple","Honey-Glazed Pork");
addRecipe("lemon+olive_oil+chicken+cream+mushroom+rice","Lemon Chicken");
addRecipe("thyme+rosemary+duck+berry_sauce","Herb Duck");
addRecipe("olive_oil+smoked_salt+meatloaf+tomato_glaze+potato","Grilled Smoked salt");
addRecipe("olive_oil+butter+braised_beef+beer+onion","Baked Butter");
addRecipe("rosemary+breaded+pork_chop+apple+sage","Roasted Breaded");
addRecipe("smoked_salt+chili+chicken+garlic+butter+parsley","Smoked Chicken");
addRecipe("butter+honey+veal+crumb+lemon","Pan-seared Honey");
addRecipe("breaded+lemon+tortilla+shrimp+chipotle+slaw","Crispy Shrimp");
addRecipe("chili+thyme+tortilla+fish+avocado+crema","Spicy Thyme");
addRecipe("honey+olive_oil+enchilada+cheese+chicken+sauce","Honey-Glazed Chicken");
addRecipe("lemon+olive_oil+taco_shell+barbacoa+onion+cilantro","Lemon Olive oil");
addRecipe("thyme+rosemary+tortilla+steak+onion+chimichurri","Herb Rosemary");
addRecipe("olive_oil+smoked_salt+tortilla+veggie+black_bean+avocado","Grilled Smoked salt");
addRecipe("olive_oil+butter+tortilla+pulled_pork+pineapple","Baked Butter");
addRecipe("rosemary+breaded+tortilla+carne_asada+chimichurri","Roasted Breaded");
addRecipe("smoked_salt+chili+tortilla+veggie_fajita+peppers+onion","Smoked Chili");
addRecipe("butter+honey+tortilla+queso+jalapeno+chipotle","Pan-seared Honey");
addRecipe("breaded+lemon+olive_oil+bread+peanut_butter+jam","Crispy Lemon");
addRecipe("chili+thyme+olive_oil+bread+cheese+butter","Spicy Thyme");
addRecipe("honey+olive_oil+rosemary+bread+bacon+lettuce+tomato+mayonnaise","Honey-Glazed Olive oil");
addRecipe("lemon+olive_oil+smoked_salt+flour+milk+egg+sugar","Lemon Olive oil");
addRecipe("thyme+rosemary+bread+egg+milk+butter","Herb Rosemary");
addRecipe("olive_oil+smoked_salt+breaded+flour+water+yeast+salt","Grilled Smoked salt");
addRecipe("olive_oil+butter+chili+rice+chicken+broth+vegetable","Baked Chicken");
addRecipe("rosemary+breaded+honey+pasta+tomato_sauce+beef","Roasted Beef");
addRecipe("smoked_salt+chili+lemon+pasta+olive_oil+garlic+parmesan","Smoked Chili");
addRecipe("butter+honey+thyme+potato+oil+salt","Pan-seared Honey");
addRecipe("breaded+lemon+olive_oil+potato+butter+milk","Crispy Lemon");
addRecipe("chili+thyme+olive_oil+tomato+broth+cream","Spicy Thyme");
addRecipe("honey+olive_oil+rosemary+chicken+broth+vegetable","Honey-Glazed Chicken");
addRecipe("olive_oil+smoked_salt+fish+lemon+butter","Lemon Olive oil");
addRecipe("thyme+rosemary+shrimp+garlic+butter","Herb Shrimp");
addRecipe("olive_oil+smoked_salt+breaded+tuna+mayonnaise+bread","Grilled Tuna");
addRecipe("olive_oil+butter+chili+egg+mayonnaise+bread","Baked Butter");
addRecipe("rosemary+breaded+honey+lettuce+parmesan+chicken","Roasted Chicken");
addRecipe("smoked_salt+chili+lemon+flatbread+cheese+chicken","Smoked Chicken");
addRecipe("butter+honey+thyme+corn_chip+cheese+jalapeno","Pan-seared Honey");
addRecipe("breaded+lemon+olive_oil+beef+potato+carrot+onion","Crispy Beef");
addRecipe("chili+thyme+olive_oil+ground_meat+tomato_sauce+herbs","Spicy Thyme");
addRecipe("honey+olive_oil+rosemary+bread+egg+cheese","Honey-Glazed Olive oil");
addRecipe("lemon+olive_oil+smoked_salt+rice+egg+soy_sauce","Lemon Olive oil");
addRecipe("thyme+rosemary+bread+butter+garlic+parsley","Herb Rosemary");
addRecipe("olive_oil+smoked_salt+breaded+potato+cheese+bacon","Grilled Smoked salt");
addRecipe("olive_oil+chili+flour+egg+milk+butter","Baked Chili");
addRecipe("rosemary+breaded+oat_seed+milk+honey","Roasted Breaded");
addRecipe("smoked_salt+chili+lemon+bread+mozzarella+tomato+basil","Smoked Chili");
addRecipe("butter+honey+thyme+avocado+lime+salt+corn_chip","Pan-seared Honey");
addRecipe("breaded+lemon+olive_oil+black_bean+rice+pepper+cheese","Crispy Lemon");
addRecipe("chili+thyme+olive_oil+lentil+carrot+onion+tomato","Spicy Thyme");
addRecipe("honey+olive_oil+rosemary+mushroom+cream+garlic","Honey-Glazed Olive oil");
addRecipe("lemon+olive_oil+smoked_salt+egg+cheese+milk","Lemon Olive oil");
addRecipe("thyme+rosemary+butter+pasta+cream+mushroom+parmesan","Herb Rosemary");
addRecipe("olive_oil+smoked_salt+breaded+tomato+sugar+vinegar+onion","Grilled Smoked salt");
addRecipe("olive_oil+butter+chili+cucumber+vinegar+sugar","Baked Butter");
addRecipe("rosemary+breaded+honey+corn+butter+salt","Roasted Breaded");

